-- Schema: comercial
-- Tabelas: 40

CREATE TABLE comercial.destacao_colecao_subcolecao (
	cod_estacao numeric(9) NULL,
	desc_estacao text NULL,
	colecao numeric(3) NULL,
	desccolecao text NULL,
	subcolecao numeric(4) NULL,
	descsubcolecao text NULL
);

CREATE TABLE comercial.dlivepro_campaign_lists (
	campaign_list_id int8 NULL,
	campaign_id int8 NULL,
	customer_cpf varchar(15) NULL,
	customer_name varchar(255) NULL,
	campaign_seller_cpf varchar(15) NULL,
	campaign_store_cnpj varchar(18) NULL,
	created_at timestamp NULL,
	contacted_at timestamp NULL,
	campaign_name varchar(255) NULL,
	campaign_name_ajusted varchar(255) NULL
);

CREATE TABLE comercial.dlivepro_campanha (
	campaigns_id int8 NULL,
	campaigns_name text NULL,
	status bool NULL,
	contact_type int4 NULL,
	repick bool NULL,
	start_when_activate bool NULL,
	start_date timestamp NULL,
	end_date timestamp NULL,
	next_impact int4 NULL,
	created_at timestamp NULL,
	audience_id int8 NULL,
	image_path text NULL,
	client_list_duration int4 NULL
);

CREATE TABLE comercial.dlivepro_transactions (
	order_id text NULL,
	transaction_status_id int8 NULL,
	customer_cpf text NULL,
	store_cnpj text NULL,
	seller_cpf text NULL,
	order_date timestamp NULL,
	coupon_discount text NULL,
	coupon_seller text NULL,
	price_paid float8 NULL,
	amount int8 NULL
);

CREATE TABLE comercial.dperiodo_venda_previsao (
	id int4 NULL,
	descricao varchar(100) NULL,
	colecao int4 NULL,
	col_tab_preco_sell_in int4 NULL,
	mes_tab_preco_sell_in int4 NULL,
	seq_tab_preco_sell_in int4 NULL,
	col_tab_preco_sell_out int4 NULL,
	mes_tab_preco_sell_out int4 NULL,
	seq_tab_preco_sell_out int4 NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.dprevisao_venda_capa (
	id varchar(50) NULL,
	id_previsao_vendas int4 NULL,
	grupo varchar(50) NULL,
	item varchar(50) NULL,
	valor_sell_in numeric(19, 6) NULL,
	valor_sell_out numeric(19, 6) NULL,
	grupo_base varchar(50) NULL,
	item_base varchar(50) NULL,
	qtde_vendida_base numeric(6) NULL,
	percentual_aplicar numeric(6, 2) NULL,
	qtde_previsao numeric(6) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.dprevisao_venda_item (
	id varchar(60) NULL,
	id_previsao_vendas int4 NULL,
	id_item_previsao_vendas varchar(60) NULL,
	grupo varchar(30) NULL,
	item varchar(30) NULL,
	sub varchar(30) NULL,
	qtde_previsao numeric(6) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.dprevisoes_vendas_colecao (
	cod_colecao int2 NULL,
	desc_colecao varchar(20) NULL,
	cod_subcolecao int2 NULL,
	desc_subcolecao varchar(20) NULL,
	classificacao int2 NULL,
	desc_classificacao varchar(6) NULL,
	abreviacao_col varchar(20) NULL,
	tipo_col varchar(20) NULL,
	data_inicio_sell_in timestamp NULL,
	data_fim_sell_in timestamp NULL,
	data_inicio_sell_out timestamp NULL,
	data_fim_sell_out timestamp NULL,
	data_inicio_producao timestamp NULL,
	data_fim_producao timestamp NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.drepresentante (
	pk_representante varchar(6) NULL,
	cnpj_repres int8 NULL,
	cod_empresa int2 NULL,
	cod_repres int2 NULL,
	nome_repres varchar(50) NULL,
	nome_fantasia varchar(50) NULL,
	tipo_repres int2 NULL,
	endereco varchar(60) NULL,
	bairro varchar(20) NULL,
	cidade varchar(40) NULL,
	regiao varchar(20) NULL,
	subregiao varchar(20) NULL,
	cep int4 NULL,
	ddd_celular int2 NULL,
	num_celular int4 NULL,
	fone_repres int4 NULL,
	inscricao_estadual varchar(14) NULL,
	email varchar(60) NULL,
	situacao int2 NULL,
	conta_banco varchar(15) NULL,
	cod_agencia varchar(15) NULL,
	cod_adm int2 NULL,
	ult_pedido timestamp NULL,
	dias_ult_pedido float8 NULL,
	dt_primeiro_pedido timestamp NULL,
	dthora_atualizacao timestamp NULL,
	cod_cidade varchar(5) NULL
);

CREATE TABLE comercial.fcontratos_locacao_lecom (
	cod_processo_f int4 NULL,
	cod_etapa_f int2 NULL,
	cod_ciclo_f int2 NULL,
	nome_contrato varchar(50) NULL,
	tipo_contrato varchar(50) NULL,
	cnpj varchar(30) NULL,
	cnpj_live varchar(30) NULL,
	cnpj_filial varchar(30) NULL,
	grupo_live varchar(200) NULL,
	depart_solicitante varchar(30) NULL,
	finalidade_locacao varchar(50) NULL,
	nome_completo varchar(80) NULL,
	cpf varchar(14) NULL,
	cpf_rep_legal varchar(14) NULL,
	email varchar(50) NULL,
	nome_empreendimento varchar(30) NULL,
	area_metros_quadrados varchar(25) NULL,
	endereco varchar(50) NULL,
	numero varchar(10) NULL,
	bairro varchar(50) NULL,
	cep varchar(12) NULL,
	cidade varchar(50) NULL,
	estado varchar(2) NULL,
	pais varchar(30) NULL,
	data_inicio_vigencia timestamp NULL,
	data_fim_vigencia timestamp NULL,
	percentual_aluguel varchar(25) NULL,
	indice_reajuste varchar(255) NULL,
	periodicidade_reajuste varchar(25) NULL,
	carencia_aluguel varchar(25) NULL,
	fundo_promocao varchar(25) NULL,
	cdu varchar(25) NULL,
	aluguel_escalonado varchar(255) NULL,
	ultima_atualizacao timestamp NULL,
	cronograma_atividades varchar(206) NULL,
	tipo_imovel varchar(207) NULL,
	matriz_filial varchar(200) NULL,
	tipo_solicitacao varchar(200) NULL,
	tipo_locacao varchar(200) NULL,
	tipo_da_locacao varchar(200) NULL,
	objeto_contrato varchar(2000) NULL,
	valor_contratado numeric(18, 3) NULL,
	valor_multa numeric(18, 3) NULL,
	razao_social varchar(180) NULL,
	fiador varchar(120) NULL,
	ide_finalizado varchar(60) NULL
);

CREATE TABLE comercial.festoque_produtos (
	fk_produto varchar(111) NULL,
	cod_erp varchar(111) NULL,
	conta_estoque int2 NULL,
	unidade_medida varchar(2) NULL,
	qtd_sugerida numeric(18, 3) NULL,
	qtd_empenhada numeric(18, 3) NULL,
	qtd_est_atual numeric(18, 3) NULL,
	qtd_disponivel numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.fitens_pedidos (
	pedido_venda int4 NULL,
	seq_item int2 NULL,
	fk_produto varchar(35) NULL,
	cod_nat_op int2 NULL,
	descr_nat_oper varchar(40) NULL,
	qtd_sugerida numeric(18, 3) NULL,
	qtd_afaturar numeric(18, 3) NULL,
	qtd_faturada numeric(18, 3) NULL,
	valor_unitario numeric(19, 4) NULL,
	percentual_desc numeric(17, 2) NULL,
	situacao_fatu_it int2 NULL,
	cod_cancelamento int2 NULL,
	tabela_preco varchar(35) NULL,
	qtd_cancelada numeric(18, 3) NULL,
	valor_cancelado numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.flivepro_conversao_campanha (
	order_id text NULL,
	order_date timestamp NULL,
	contacted_at timestamp NULL,
	campaign_list_id int8 NULL,
	campaign_id int8 NULL,
	tempo_conversao text NULL
);

CREATE TABLE comercial.flog_itens_transfer (
	cd_pedido int4 NULL,
	cd_pedido_cliente varchar(100) NULL,
	seq_item_pedido int2 NULL,
	cd_item_trans varchar(60) NULL,
	cd_destino_venda int4 NULL,
	cd_destino_cliente varchar(100) NULL,
	seq_item_destino int4 NULL,
	qtd_transferida numeric(18, 3) NULL,
	controle int2 NULL,
	dt_hora_insercao timestamp NULL,
	usuario_alteracao varchar(100) NULL,
	nome_usuario varchar(120) NULL,
	empresa_usuario int2 NULL,
	situacao_usuario_empresa varchar(15) NULL,
	observacao_usuario varchar(120) NULL
);

CREATE TABLE comercial.flog_pedidos_itens_cancelados (
	numero_pedido numeric(9) NULL,
	seq_item_pedido numeric(3) NULL,
	tipo_ocorr text NULL,
	sku text NULL,
	cod_cancelamento_capa numeric(3) NULL,
	cod_cancelamento_item numeric(3) NULL,
	qtdcancelada numeric(38, 10) NULL,
	data_ocorrencia timestamp NULL,
	nome_programa text NULL,
	aplicacao text NULL,
	usuario_rede text NULL
);

CREATE TABLE comercial.flog_pedidos_itens_transferidos (
	numero_pedido numeric(9) NULL,
	seq_item_pedido numeric(3) NULL,
	tipo_ocorr text NULL,
	desc_tipo_ocorrencia text NULL,
	sequencia_origem numeric(38, 10) NULL,
	sequencia_destino numeric(38, 10) NULL,
	produto_destino text NULL,
	pedido_destino numeric(38, 10) NULL,
	sku text NULL,
	qtd_transferida numeric(38, 10) NULL,
	cod_cancelamento numeric(38, 10) NULL,
	desc_canc_item text NULL,
	data_ocorr timestamp NULL,
	nome_programa text NULL,
	usuario_rede text NULL,
	nome_usuario text NULL
);

CREATE TABLE comercial.fmeta_categorias_orion (
	cod_estacao numeric(9) NULL,
	catalogo numeric(4) NULL,
	descricao text NULL,
	id text NULL,
	cod_canal numeric(6) NULL,
	canal text NULL,
	cod_representante numeric(6) NULL,
	tipo_meta numeric(1) NULL,
	valor_categoria_1 numeric(12, 4) NULL,
	valor_categoria_2 numeric(12, 4) NULL,
	valor_categoria_3 numeric(12, 4) NULL,
	valor_categoria_4 numeric(12, 4) NULL,
	valor_categoria_5 numeric(12, 4) NULL,
	valor_categoria_6 numeric(12, 4) NULL,
	valor_categoria_7 numeric(12, 4) NULL,
	valor_categoria_8 numeric(12, 4) NULL,
	valor_categoria_9 numeric(12, 4) NULL,
	valor_categoria_10 numeric(12, 4) NULL
);

CREATE TABLE comercial.fmeta_estacao_orion (
	cod_estacao numeric(9) NULL,
	catalogo numeric(4) NULL,
	descricao text NULL,
	cod_canal numeric(6) NULL,
	canal text NULL,
	cod_representante numeric(6) NULL,
	descricao_rep text NULL,
	tipo_meta numeric(3) NULL,
	meta numeric(9, 2) NULL
);

CREATE TABLE comercial.fmeta_representante (
	cod_estacao int4 NULL,
	descricao varchar(150) NULL,
	tabela_preco varchar(35) NULL,
	cod_representante int4 NULL,
	descricao_rep varchar(100) NULL,
	cod_canal int4 NULL,
	canal varchar(50) NULL,
	tipo_meta int2 NULL,
	meta numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.fmeta_representante_orion (
	cod_estacao numeric(9) NULL,
	catalogo numeric(4) NULL,
	descricao text NULL,
	cod_canal numeric(6) NULL,
	canal text NULL,
	cod_representante numeric(6) NULL,
	descricao_rep text NULL,
	tipo_meta numeric(3) NULL,
	meta numeric(9, 2) NULL
);

CREATE TABLE comercial.fmeta_tabpreco_orion (
	cod_estacao numeric(9) NULL,
	catalogo numeric(4) NULL,
	descricao text NULL,
	id text NULL,
	col_tab numeric(3) NULL,
	mes_tab numeric(3) NULL,
	seq_tab numeric(3) NULL
);

CREATE TABLE comercial.fmovimentos_lojas_usa (
	id varchar(100) NULL,
	"name" varchar(50) NULL,
	createdat timestamp NULL,
	processedat timestamp NULL,
	customer varchar(100) NULL,
	sourceidentifier varchar(150) NULL,
	confirmed bool NULL,
	paymentgatewaynames varchar(255) NULL,
	currencycode varchar(20) NULL,
	financialstatus varchar(50) NULL,
	subtotalamount numeric(18, 3) NULL,
	totaldiscountsamount numeric(18, 3) NULL,
	totaltaxamount numeric(18, 3) NULL,
	valorfaturamento numeric(18, 3) NULL,
	valorrefund numeric(18, 3) NULL,
	valorcaixa numeric(18, 3) NULL,
	sku varchar(100) NULL,
	product varchar(200) NULL,
	quantity int4 NULL,
	originalunitpriceamount numeric(18, 3) NULL,
	store varchar(50) NULL
);

CREATE TABLE comercial.fnotas_canceladas (
	serie_nota_fisc varchar(3) NULL,
	num_nota_fiscal int4 NULL,
	num_pedido int4 NULL,
	data_emissao timestamp NULL,
	cod_canc_nfisc int2 NULL,
	motivo_cancel varchar(30) NULL,
	situacao_duplic int2 NULL,
	situacao varchar(12) NULL,
	flag varchar(32) NULL,
	natur_operacao int2 NULL,
	descr_nat_oper varchar(40) NULL,
	pk_cliente varchar(4000) NULL,
	cod_forma_pagto int2 NULL,
	desc_forma_pagto varchar(30) NULL,
	cod_cond_pgto int2 NULL,
	desc_cond_pgto varchar(30) NULL,
	qtde_itens int4 NULL,
	valor_desconto numeric(18, 3) NULL,
	valor_itens_nfis numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.fnotas_venda_produtos (
	nf_serienotafiscal varchar(3) NULL,
	nf_notafiscal int4 NULL,
	nf_nrpedidovenda int4 NULL,
	nf_cdempresa int8 NULL,
	pk_cliente varchar(25) NULL,
	nf_dataemissao timestamp NULL,
	data_embarque timestamp NULL,
	desc_forma_pgto varchar(30) NULL,
	nf_condpgto int2 NULL,
	desc_condpgto varchar(30) NULL,
	nf_cod_situacao int8 NULL,
	nf_desc_situacao varchar(10) NULL,
	canal varchar(100) NULL,
	modalidade varchar(50) NULL,
	nf_cod_natureza int2 NULL,
	uf varchar(2) NULL,
	desc_nat_oper varchar(40) NULL,
	tipo_nota varchar(32) NULL,
	ultima_atualizacao timestamp NULL,
	pk_produto varchar(18) NULL,
	nf_nrseqitempedido int8 NULL,
	nf_formapgto int8 NULL,
	itemnf_qtdfaturada numeric(18, 3) NULL,
	itemnf_vlrunit numeric(18, 3) NULL,
	itemnf_vlr_contabil numeric(18, 3) NULL,
	itemnf_vlr_tot numeric(18, 3) NULL,
	itemnf_vlr_franchising numeric(18, 3) NULL,
	cod_representante int4 NULL
);

CREATE TABLE comercial.fpaypal_liberadas (
	id numeric(9) NULL,
	usuario_liberador text NULL,
	data_liberacao timestamp NULL,
	data_insercao timestamp NULL,
	nota_fiscal numeric(9) NULL,
	serie_nota text NULL,
	status numeric(1) NULL,
	cliente text NULL,
	nome_cliente text NULL,
	cod_empresa text NULL,
	cgc_9 numeric(9) NULL,
	cgc_4 numeric(4) NULL,
	cgc_2 numeric(2) NULL,
	cond_pagamento text NULL,
	valor_nota numeric(38, 10) NULL,
	pedido_refaturamento numeric(38, 10) NULL,
	representante text NULL,
	tipo_cliente text NULL,
	origem text NULL,
	canal text NULL
);

CREATE TABLE comercial.fpaypal_nao_liberadas (
	id numeric(9) NULL,
	usuario_liberador text NULL,
	data_liberacao timestamp NULL,
	data_insercao timestamp NULL,
	nota_fiscal numeric(9) NULL,
	serie_nota text NULL,
	status numeric(1) NULL,
	cpf_cnpj_cliente text NULL,
	nome_cliente text NULL,
	cod_empresa text NULL,
	cgc_9 numeric(9) NULL,
	cgc_4 numeric(4) NULL,
	cgc_2 numeric(2) NULL,
	cond_pagamento text NULL,
	valor_nota numeric(38, 10) NULL,
	pedido_refaturamento numeric(38, 10) NULL,
	representante text NULL,
	tipo_cliente text NULL,
	dias_emissao numeric(38, 10) NULL,
	origem text NULL,
	canal text NULL,
	volume numeric(38, 10) NULL
);

CREATE TABLE comercial.fpedido (
	fk_produto varchar(25) NULL,
	ped_cdempresa int2 NULL,
	ped_cdrep int4 NULL,
	ped_cdpedido int4 NULL,
	ped_refproduto varchar(5) NULL,
	ped_dataemissao timestamp NULL,
	ped_dataembarque timestamp NULL,
	ped_codcancelamento int2 NULL,
	ped_prazomedio int2 NULL,
	ped_periodo int2 NULL,
	ped_cdcidade int4 NULL,
	ped_tabelapreco int4 NULL,
	ped_numerocontrole int2 NULL,
	ped_pedidovendaorigem int4 NULL,
	ped_pedidoorigem int4 NULL,
	ped_cfop varchar(5) NULL,
	ped_percomissaoped numeric(18, 3) NULL,
	ped_percdescped numeric(18, 3) NULL,
	ped_aceitaantecipacao int2 NULL,
	ped_aceitaantecipacaodesc varchar(3) NULL,
	permite_parcial varchar(3) NULL,
	ped_tipofrete int2 NULL,
	ped_condicaopagamento int2 NULL,
	ped_codigobanco int2 NULL,
	ped_percdescontotitulo numeric(18, 3) NULL,
	ped_pedidocliente varchar(30) NULL,
	itemped_qtdcancelada float8 NULL,
	itemped_valorcancelado numeric(18, 3) NULL,
	itemped_qtdsaldopedido float8 NULL,
	itemped_valorsaldopedido numeric(18, 3) NULL,
	itemped_qtdepedido numeric(18, 3) NULL,
	itemped_qtdeliqpedido numeric(18, 3) NULL,
	itemped_percdescontoitem numeric(18, 3) NULL,
	itemped_valorliqpedido numeric(18, 3) NULL,
	itemped_valorcomissao numeric(18, 3) NULL,
	itemped_valordescped numeric(18, 3) NULL,
	itemped_codcancelamento int2 NULL,
	itemped_datacancelamento timestamp NULL,
	itemped_desccancel varchar(20) NULL,
	itemped_tipocancelamento int2 NULL,
	itemped_cdcolecao int2 NULL,
	itemped_vlrdescontoitens numeric(18, 3) NULL,
	itemped_vlrtotalbruto numeric(18, 3) NULL,
	itemped_vlrtotalfaturado numeric(18, 3) NULL,
	itemped_valorunitario numeric(18, 3) NULL,
	itemped_seqitem int2 NULL,
	itemped_codigodeposito int2 NULL,
	fk_cliente varchar(20) NULL,
	fk_representante varchar(6) NULL,
	ped_classificacao int4 NULL,
	ped_funcionario int4 NULL,
	ped_moeda varchar(20) NULL,
	ped_cod_situacao_venda varchar(2) NULL,
	dthora_atualizacao timestamp NULL,
	itemped_qtdsugerida numeric(15, 3) NULL,
	itemped_qtdafaturar numeric(18, 3) NULL,
	ped_cod_natureza int2 NULL,
	itemped_cod_natureza int2 NULL,
	ped_desconto1 numeric(18, 3) NULL,
	ped_desconto2 numeric(18, 3) NULL,
	ped_desconto3 numeric(18, 3) NULL,
	ped_desconto_especial numeric(18, 3) NULL,
	ped_valor_despesas numeric(18, 3) NULL,
	ped_desconto_item_1 numeric(18, 3) NULL,
	ped_desconto_item_2 numeric(18, 3) NULL,
	ped_desconto_item_3 numeric(18, 3) NULL,
	itemped_vlr_franchising numeric(18, 3) NULL,
	itemped_qtd_faturada numeric(18, 3) NULL,
	natureza_venda varchar(3) NULL,
	origem_pedido int2 NULL,
	tipo_cliente int2 NULL,
	despesas_adicionais numeric(18, 3) NULL,
	ped_tipo_carteira varchar(14) NULL,
	canal varchar(100) NULL,
	flag_regra varchar(14) NULL,
	itemped_valoruni_bruto numeric(18, 3) NULL,
	codigo_barras varchar(16) NULL
);

CREATE TABLE comercial.fpedido_showroom (
	fk_produto varchar(25) NULL,
	ped_cdempresa int2 NULL,
	ped_cdrep int4 NULL,
	ped_cdpedido int4 NULL,
	ped_refproduto varchar(5) NULL,
	ped_dataemissao timestamp NULL,
	ped_dataembarque timestamp NULL,
	ped_codcancelamento int2 NULL,
	ped_prazomedio int2 NULL,
	ped_periodo int2 NULL,
	ped_cdcidade int4 NULL,
	ped_tabelapreco int4 NULL,
	ped_numerocontrole int2 NULL,
	ped_pedidovendaorigem int4 NULL,
	ped_pedidoorigem int4 NULL,
	ped_cfop varchar(5) NULL,
	ped_percomissaoped numeric(18, 3) NULL,
	ped_percdescped numeric(18, 3) NULL,
	ped_aceitaantecipacao int2 NULL,
	ped_aceitaantecipacaodesc varchar(3) NULL,
	permite_parcial varchar(3) NULL,
	ped_tipofrete int2 NULL,
	ped_condicaopagamento int2 NULL,
	ped_codigobanco int2 NULL,
	ped_percdescontotitulo numeric(18, 3) NULL,
	ped_pedidocliente varchar(30) NULL,
	itemped_qtdcancelada float8 NULL,
	itemped_valorcancelado numeric(18, 3) NULL,
	itemped_qtdsaldopedido float8 NULL,
	itemped_valorsaldopedido numeric(18, 3) NULL,
	itemped_qtdepedido numeric(18, 3) NULL,
	itemped_qtdeliqpedido numeric(18, 3) NULL,
	itemped_percdescontoitem numeric(18, 3) NULL,
	itemped_valorliqpedido numeric(18, 3) NULL,
	itemped_valorcomissao numeric(18, 3) NULL,
	itemped_valordescped numeric(18, 3) NULL,
	itemped_codcancelamento int2 NULL,
	itemped_datacancelamento timestamp NULL,
	itemped_desccancel varchar(20) NULL,
	itemped_tipocancelamento int2 NULL,
	itemped_cdcolecao int2 NULL,
	itemped_vlrdescontoitens numeric(18, 3) NULL,
	itemped_vlrtotalbruto numeric(18, 3) NULL,
	itemped_vlrtotalfaturado numeric(18, 3) NULL,
	itemped_valorunitario numeric(18, 3) NULL,
	itemped_seqitem int2 NULL,
	itemped_codigodeposito int2 NULL,
	fk_cliente varchar(20) NULL,
	fk_representante varchar(6) NULL,
	ped_classificacao int4 NULL,
	ped_funcionario int4 NULL,
	ped_moeda varchar(20) NULL,
	ped_cod_situacao_venda varchar(2) NULL,
	dthora_atualizacao timestamp NULL,
	itemped_qtdsugerida numeric(15, 3) NULL,
	itemped_qtdafaturar numeric(18, 3) NULL,
	ped_cod_natureza int2 NULL,
	itemped_cod_natureza int2 NULL,
	ped_desconto1 numeric(18, 3) NULL,
	ped_desconto2 numeric(18, 3) NULL,
	ped_desconto3 numeric(18, 3) NULL,
	ped_desconto_especial numeric(18, 3) NULL,
	ped_valor_despesas numeric(18, 3) NULL,
	ped_desconto_item_1 numeric(18, 3) NULL,
	ped_desconto_item_2 numeric(18, 3) NULL,
	ped_desconto_item_3 numeric(18, 3) NULL,
	itemped_vlr_franchising numeric(18, 3) NULL,
	itemped_qtd_faturada numeric(18, 3) NULL,
	natureza_venda varchar(3) NULL,
	origem_pedido int2 NULL,
	tipo_cliente int2 NULL,
	despesas_adicionais numeric(18, 3) NULL,
	ped_tipo_carteira varchar(14) NULL,
	canal varchar(100) NULL,
	flag_regra varchar(14) NULL,
	itemped_valoruni_bruto numeric(18, 3) NULL,
	codigo_barras varchar(16) NULL,
	showroom_id int4 NULL
);

CREATE TABLE comercial.fpedido_situacao_bloqueio (
	pedido_venda numeric(9) NULL,
	seq_situacao numeric(2) NULL,
	codigo_situacao numeric(2) NULL,
	data_situacao timestamp NULL,
	flag_liberacao text NULL,
	desc_liberacao text NULL,
	data_liberacao timestamp NULL,
	responsavel text NULL,
	observacao text NULL,
	usuario_bloqueio text NULL,
	executa_trigger numeric(1) NULL
);

CREATE TABLE comercial.fpedidos_capa (
	pedido_venda int4 NULL,
	codigo_empresa int2 NULL,
	data_emissao timestamp NULL,
	data_embarque timestamp NULL,
	cd_representante int4 NULL,
	descr_nat_oper varchar(40) NULL,
	tipo_carteira varchar(32) NULL,
	estado_atual varchar(10) NULL,
	cod_cancelamento int2 NULL,
	motivo varchar(60) NULL,
	canal varchar(100) NULL,
	desc_cond_pgto varchar(30) NULL,
	cod_forma_pagto int4 NULL,
	desc_forma_pgto varchar(30) NULL,
	situacao_venda int2 NULL,
	desc_situacao_venda varchar(37) NULL,
	tipo_comissao int2 NULL,
	percent_comissao numeric(18, 3) NULL,
	tabela_preco varchar(35) NULL,
	cod_cidade int4 NULL,
	qtde_saldo_pedi numeric(18, 3) NULL,
	qtde_total_pedi numeric(18, 3) NULL,
	valor_saldo_pedi numeric(17, 2) NULL,
	valor_liquido numeric(17, 2) NULL,
	valor_bruto numeric(17, 2) NULL,
	ultima_atualizacao timestamp NULL,
	cnpj_cliente varchar(30) NULL
);

CREATE TABLE comercial.fpedidos_em_aberto (
	sku varchar(20) NULL,
	codigo_empresa varchar(3) NULL,
	data_emissao timestamp NULL,
	data_embarque timestamp NULL,
	descr_nat_oper varchar(60) NULL,
	cod_cancelamento varchar(3) NULL,
	motivo varchar(60) NULL,
	situacao_venda varchar(2) NULL,
	desc_situacao_venda varchar(40) NULL,
	estado_atual varchar(15) NULL,
	quantidade_pedido int8 NULL,
	qtdcancelada int8 NULL,
	qtdsaldopedido int8 NULL,
	ultima_atualizacao timestamp NULL,
	pedido_venda varchar(20) NULL,
	canal varchar(35) NULL
);

CREATE TABLE comercial.fpedidos_itens_cancelados (
	numero_pedido numeric(9) NULL,
	seq_item_pedido numeric(3) NULL,
	tipo_ocorr text NULL,
	desc_tipo_ocorrencia text NULL,
	sku text NULL,
	qtde_pedida_old numeric(16, 3) NULL,
	qtde_pedida_new numeric(16, 3) NULL,
	cod_cancelamento numeric(3) NULL,
	desc_canc_pedido text NULL,
	data_ocorr timestamp NULL,
	nome_programa text NULL,
	usuario_rede text NULL,
	nome_usuario text NULL,
	empresa_usuario numeric(3) NULL,
	situacao_usuario_empresa text NULL,
	observacao_usuario text NULL
);

CREATE TABLE comercial.fpedidos_refaturados (
	pedido numeric(9) NULL,
	cnpj_cliente text NULL,
	notaref numeric(9) NULL,
	dataemissaoref text NULL,
	condpagtoref text NULL,
	notadevolucao numeric(9) NULL,
	motivo text NULL,
	usuariocardex text NULL,
	notageradaref numeric(9) NULL,
	dataemissaonotageradaref text NULL,
	condpagtonotageradaref text NULL,
	valornota numeric(13, 2) NULL
);

CREATE TABLE comercial.frastreio_entrega_loja (
	pedido_venda int4 NULL,
	serie_nota_fiscal varchar(3) NULL,
	numero_nota_fiscal int4 NULL,
	numero_minuta int4 NULL,
	rastreador_tms varchar(100) NULL,
	ultima_atualizacao timestamp NULL,
	data_envio timestamp NULL
);

CREATE TABLE comercial.fregiao_representante (
	cod_representante int4 NULL,
	cod_cidade int4 NULL,
	cod_adm int4 NULL,
	nome_adm varchar(40) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.fsaldos_estoque_mes (
	codigo_deposito int2 NULL,
	desc_deposito varchar(30) NULL,
	pk_produto varchar(30) NULL,
	nivel_produto varchar(1) NULL,
	referencia varchar(5) NULL,
	tamanho varchar(3) NULL,
	cor varchar(6) NULL,
	mes_ano_movimento timestamp NULL,
	ano_movimento int2 NULL,
	mes_movimento int2 NULL,
	saldo_fisico numeric(18, 3) NULL,
	saldo_financeiro numeric(18, 3) NULL,
	saldo_financeiro_estimado numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE comercial.fshopify_movimentacoes_ecom_internacional (
	numero_pedido numeric(20) NULL,
	order_date timestamp NULL,
	tms_tracker text NULL,
	carrier_tracker text NULL,
	trasnportadora text NULL,
	"type" text NULL,
	country_code text NULL,
	country text NULL,
	currency text NULL,
	shipping_value float8 NULL,
	current_total_duties float8 NULL,
	total_tax float8 NULL,
	total_discounts float8 NULL,
	current_subtotal_price float8 NULL,
	valor_total_pedido float8 NULL,
	valor_pago float8 NULL
);

CREATE TABLE comercial.fshopify_orders (
	id int8 NULL,
	shopify_id int8 NULL,
	order_number int8 NULL,
	order_date timestamp NULL,
	customer_id int8 NULL,
	source_identifier varchar(200) NULL,
	confirmed int8 NULL,
	payment_gateway_names varchar(200) NULL,
	currency varchar(255) NULL,
	total_discounts numeric(18, 3) NULL,
	total_price numeric(18, 3) NULL
);

CREATE TABLE comercial.fshopify_orders_itens (
	order_id int8 NULL,
	sku varchar(50) NULL,
	shopify_product_id int8 NULL,
	quantity int4 NULL,
	price numeric(17, 2) NULL,
	desconto_code varchar(40) NULL,
	desconto_valor numeric(17, 2) NULL
);

CREATE TABLE comercial.ftitulos_venda (
	pedido_venda int4 NULL,
	serie_nota_fisc varchar(3) NULL,
	nf_notafiscal int4 NULL,
	num_nota_fiscal int8 NULL,
	sequencia int2 NULL,
	cod_forma_pagto int2 NULL,
	desc_forma_pgto varchar(30) NULL,
	situacao_duplic int2 NULL,
	desc_situacao varchar(12) NULL,
	valor_duplicata numeric(18, 3) NULL,
	saldo_duplicata numeric(18, 3) NULL,
	valor_pago numeric(18, 3) NULL,
	historico_pgto int2 NULL,
	historico_contab varchar(30) NULL,
	ultima_atualizacao timestamp NULL
);