-- Schema: eventos
-- Tabelas: 9

CREATE TABLE eventos.dinfo_eventos (
	id int8 NULL,
	nome_evento text NULL,
	nome text NULL,
	primeira_corrida text NULL,
	email text NULL,
	cpf varchar(20) NULL,
	cpf_responsavel varchar(20) NULL,
	data_aniversario date NULL,
	genero varchar(20) NULL,
	pcd int4 NULL,
	celular varchar(20) NULL,
	kit text NULL,
	subtotal numeric(12, 2) NULL,
	desconto numeric(12, 2) NULL,
	total numeric(12, 2) NULL,
	nome_time text NULL,
	informacao_adicional text NULL,
	status varchar(50) NULL,
	origem varchar(50) NULL,
	numer_peito varchar(50) NULL,
	check_in varchar(20) NULL,
	data_registro timestamp NULL
);

CREATE TABLE eventos.ditens_carrinho (
	id serial4 NOT NULL,
	id_cart int4 NULL,
	order_id int4 NULL,
	event_id int4 NULL,
	order_date date NULL,
	"name" varchar(100) NULL,
	"size" varchar(20) NULL,
	price_full numeric NULL,
	price_paid numeric NULL,
	discount numeric NULL,
	CONSTRAINT ditens_carrinho_pkey PRIMARY KEY (id)
);

CREATE TABLE eventos.fcreditos_eventos (
	cod_empresa numeric(3) NULL,
	exercicio numeric(4) NULL,
	numero_lanc numeric(9) NULL,
	seq_lanc numeric(5) NULL,
	origem numeric(2) NULL,
	lote numeric(5) NULL,
	periodo numeric(4) NULL,
	conta_contabil text NULL,
	conta_reduzida numeric(5) NULL,
	subconta numeric(4) NULL,
	centro_custo numeric(6) NULL,
	debito_credito text NULL,
	hist_contabil numeric(4) NULL,
	compl_histor1 text NULL,
	data_lancto timestamp NULL,
	valor_lancto numeric(15, 2) NULL,
	filial_lancto numeric(3) NULL,
	contabilizado numeric(1) NULL,
	data_contab timestamp NULL,
	documento numeric(9) NULL,
	datainsercao timestamp NULL
);

CREATE TABLE eventos.fdebitos_eventos (
	cod_empresa numeric(3) NULL,
	exercicio numeric(4) NULL,
	numero_lanc numeric(9) NULL,
	seq_lanc numeric(5) NULL,
	origem numeric(2) NULL,
	lote numeric(5) NULL,
	periodo numeric(4) NULL,
	conta_contabil text NULL,
	conta_reduzida numeric(5) NULL,
	subconta numeric(4) NULL,
	centro_custo numeric(6) NULL,
	debito_credito text NULL,
	hist_contabil numeric(4) NULL,
	compl_histor1 text NULL,
	data_lancto timestamp NULL,
	valor_lancto numeric(15, 2) NULL,
	filial_lancto numeric(3) NULL,
	contabilizado numeric(1) NULL,
	data_contab timestamp NULL,
	documento numeric(9) NULL,
	datainsercao timestamp NULL
);

CREATE TABLE eventos.fexperience_events (
	id int8 NULL,
	event_id int8 NULL,
	event_name text NULL,
	event_status text NULL,
	event_type text NULL,
	modality text NULL,
	registration_limit int8 NULL,
	distance text NULL,
	start_time text NULL,
	min_subscription_age int8 NULL,
	max_subscription_age int8 NULL,
	event_date date NULL,
	subscriptions_opened date NULL,
	subscriptions_closed date NULL,
	event_address text NULL,
	event_photo text NULL,
	results_link text NULL,
	start_location text NULL,
	"map" text NULL,
	event_description text NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL
);

CREATE TABLE eventos.fexperience_registrations (
	id int8 NULL,
	event_id int8 NULL,
	modality text NULL,
	distance text NULL,
	chest_number text NULL,
	store_cnpj text NULL,
	store_name text NULL,
	cpf_cnpj text NULL,
	birthday date NULL,
	gender text NULL,
	order_date timestamp NULL,
	order_id text NULL,
	order_status text NULL,
	coupon text NULL,
	coupon_group text NULL,
	payment_type text NULL,
	kit text NULL,
	cart_items text NULL,
	price_paid float8 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL
);

CREATE TABLE eventos.fnotas_compras_eventos (
	serie text NULL,
	documento numeric(9) NULL,
	sequencia numeric(9) NULL,
	centro_custo numeric(9) NULL,
	nome_centro_custo text NULL,
	especie_docto text NULL,
	data_transacao timestamp NULL,
	data_emissao timestamp NULL,
	cod_produto text NULL,
	descricao_item text NULL,
	desc_natureza_oper text NULL,
	cod_situacao_nota numeric(1) NULL,
	desc_situacao_nota text NULL,
	codigo_cancelamento_pedido numeric(2) NULL,
	desc_cancelamento_pedido text NULL,
	data_canc_nfisc timestamp NULL,
	cnpj_fornecedor text NULL,
	nome_fornecedor text NULL,
	cod_tipo_fornecedor numeric(4) NULL,
	desc_tipo_fornecedor text NULL,
	desc_cond_pgto text NULL,
	unidade_medida text NULL,
	quantidade numeric(14, 3) NULL,
	valor_unitario numeric(20, 5) NULL,
	valor_total numeric(15, 2) NULL,
	data_atualizacao timestamp NULL
);

CREATE TABLE eventos.fpedidos_compra_eventos (
	pedido_compra numeric(6) NULL,
	seq_item_pedido numeric(3) NULL,
	numero_compra_obc text NULL,
	num_requisicao numeric(6) NULL,
	centro_custo numeric(6) NULL,
	nome_centro_custo text NULL,
	data_prev_entr timestamp NULL,
	dt_emis_ped_comp timestamp NULL,
	cod_produto text NULL,
	descricao_item text NULL,
	cod_situacao_nota numeric(1) NULL,
	sts_pedido_desc text NULL,
	codigo_cancelamento_pedido numeric(2) NULL,
	desc_cancelamento_pedido text NULL,
	codigo_cancelamento_item numeric(2) NULL,
	desc_cancelamento_item text NULL,
	cnpj_fornecedor text NULL,
	nome_fornecedor text NULL,
	cod_tipo_fornecedor numeric(4) NULL,
	desc_tipo_fornecedor text NULL,
	unidade_medida text NULL,
	qtde_saldo_item numeric(15, 3) NULL,
	qtde_pedida_item numeric(15, 3) NULL,
	preco_item_comp numeric(15, 5) NULL,
	data_atualizacao timestamp NULL
);

CREATE TABLE eventos.ftitulos_compras_eventos (
	documento varchar(10) NULL,
	centro_custo varchar(10) NULL,
	nome_centro_custo varchar(40) NULL,
	especie_docto varchar(5) NULL,
	data_transacao timestamp NULL,
	data_emissao timestamp NULL,
	codigo_contabil varchar(10) NULL,
	codigo_cancelamento_pedido varchar(5) NULL,
	desc_cancelamento_pedido varchar(80) NULL,
	data_canc_tit timestamp NULL,
	cnpj_fornecedor varchar(15) NULL,
	nome_fornecedor varchar(60) NULL,
	cod_tipo_fornecedor varchar(4) NULL,
	forn_descricao varchar(40) NULL,
	cond_pagto varchar(3) NULL,
	valor_parcela numeric(17, 2) NULL
);