-- Schema: financeiro
-- Tabelas: 6

CREATE TABLE financeiro.dconsulta_nfs (
	num_nota_fiscal varchar(50) NULL,
	serie_nota_fisc varchar(20) NULL,
	especie_docto varchar(20) NULL,
	data_base_fatur date NULL,
	data_saida date NULL,
	data_prevista date NULL,
	cod_rep_cliente varchar(50) NULL,
	pedido_venda varchar(50) NULL,
	usuario_digitacao varchar(100) NULL,
	valor_itens_nfis numeric(15, 2) NULL,
	valor_desconto numeric(15, 2) NULL,
	situacao_nfisc varchar(20) NULL
);

CREATE TABLE financeiro.dlancamentos_contabeis (
	exercicio numeric(4) NULL,
	data_lancto timestamp NULL,
	cod_empresa numeric(3) NULL,
	desc_empresa text NULL,
	conta_contabil text NULL,
	conta_reduzida numeric(5) NULL,
	centro_custo numeric(6) NULL,
	desc_ccusto text NULL,
	chave numeric(9) NULL,
	seqchave numeric(5) NULL,
	cod_contabil numeric(4) NULL,
	desc_historico text NULL,
	complemento_historico text NULL,
	debito numeric(38, 10) NULL,
	credito numeric(38, 10) NULL,
	desc_plano_conta text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE financeiro.fapuracao_notas_entrada (
	codigo_empresa numeric(3) NULL,
	data_transacao timestamp NULL,
	codificacao_contabil numeric(38, 10) NULL,
	classificacao_fiscal text NULL,
	documento numeric(9) NULL,
	serie text NULL,
	cgc_cli_for_9 numeric(9) NULL,
	cgc_cli_for_4 numeric(4) NULL,
	cgc_cli_for_2 numeric(2) NULL,
	data_emissao timestamp NULL,
	tipo_valores_fiscal text NULL,
	situacao_entrada numeric(1) NULL,
	rateio_despesas numeric(15, 2) NULL,
	classif_contabil numeric(6) NULL,
	cod_natureza text NULL,
	descr_nat_oper text NULL,
	livros_fiscais numeric(1) NULL,
	divisao_natur numeric(2) NULL,
	natur_operacao numeric(3) NULL,
	estado_natoper text NULL,
	cod_vlfiscal_icm numeric(9) NULL,
	cod_vlfiscal_ipi numeric(9) NULL,
	base_diferenca numeric(15, 2) NULL,
	base_ipi numeric(15, 2) NULL,
	base_pis_cofins numeric(15, 2) NULL,
	base_icms_subs numeric(14, 2) NULL,
	base_icms numeric(15, 2) NULL,
	base_calc_icm numeric(15, 2) NULL,
	valor_total_ipi numeric(15, 2) NULL,
	valor_despesas numeric(15, 2) NULL,
	valor_frete numeric(15, 2) NULL,
	valor_desconto numeric(15, 2) NULL,
	valor_seguro numeric(15, 2) NULL,
	valor_ipi numeric(15, 2) NULL,
	valor_pis numeric(15, 2) NULL,
	valor_cofins numeric(15, 2) NULL,
	valor_icms numeric(15, 2) NULL,
	valor_total numeric(15, 2) NULL,
	valor_itens numeric(15, 2) NULL,
	desconta_ipi_icms numeric(15, 2) NULL
);

CREATE TABLE financeiro.fapuracao_notas_saida (
	codigo_empresa numeric(3) NULL,
	codificacao_contabil numeric(6) NULL,
	classificacao_fiscal text NULL,
	num_nota_fiscal numeric(9) NULL,
	serie_nota_fisc text NULL,
	data_emissao timestamp NULL,
	situacao_nfisc numeric(1) NULL,
	cgc_9 numeric(9) NULL,
	cgc_4 numeric(4) NULL,
	cgc_2 numeric(2) NULL,
	tipo_nf_referenciada numeric(1) NULL,
	classif_contabil_nf_item numeric(6) NULL,
	desconta_ipi_icms numeric(1) NULL,
	classif_contabil numeric(6) NULL,
	cod_natureza text NULL,
	descr_nat_oper text NULL,
	livros_fiscais numeric(1) NULL,
	divisao_natur numeric(2) NULL,
	classific_fiscal text NULL,
	natopeno_nat_oper numeric(3) NULL,
	natopeno_est_oper text NULL,
	consiste_cvf_icms numeric(1) NULL,
	rateio_despesa numeric(15, 2) NULL,
	rateio_desc_propaganda numeric(15, 2) NULL,
	isento_outros numeric(15, 2) NULL,
	cod_justificativa numeric(1) NULL,
	cvf_icms numeric(2) NULL,
	cvf_ipi numeric(1) NULL,
	cvf_icm_diferenc numeric(9) NULL,
	base_icms numeric(15, 2) NULL,
	base_icms_difer numeric(15, 2) NULL,
	basi_pis_cofins numeric(15, 2) NULL,
	perc_icms numeric(6, 2) NULL,
	perc_ipi numeric(6, 2) NULL,
	perc_reducao_icm numeric(8, 4) NULL,
	perc_substituica numeric(5, 2) NULL,
	perc_iva_1 numeric(6, 2) NULL,
	valor_icms_difer numeric(11, 2) NULL,
	valor_ipi numeric(15, 2) NULL,
	valor_pis numeric(15, 2) NULL,
	valor_icms numeric(15, 2) NULL,
	valor_cofins numeric(15, 2) NULL,
	valor_faturado numeric(15, 2) NULL,
	valor_contabil numeric(15, 2) NULL,
	valor_unitario numeric(18, 5) NULL,
	qtde_item_fatur numeric(15, 3) NULL
);

CREATE TABLE financeiro.forion_orcamento (
	id numeric(6) NULL,
	centro_custo text NULL,
	plano_ano numeric(38) NULL,
	conta text NULL,
	fornecedor text NULL,
	despesa text NULL,
	tipo_orcamento text NULL,
	cargo text NULL,
	ano numeric(4) NULL,
	mes numeric(38, 10) NULL,
	mes_ano timestamp NULL,
	quantidade numeric(3) NULL,
	valor_orcado numeric(10, 2) NULL
);

CREATE TABLE financeiro.ftitulos_receber_resumo (
	num_titulo text NULL,
	cnpj_cliente text NULL,
	pk_cliente text NULL,
	nome_cliente text NULL,
	descricao text NULL,
	cod_situa_duplic numeric(1) NULL,
	val_desconto numeric(15, 2) NULL,
	val_pago numeric(38, 10) NULL,
	dat_ult_pagto_aux timestamp NULL
);