-- Schema: jma
-- Tabelas: 71

CREATE TABLE jma.confer_caixas (
	codigo_transferencia varchar(18) NULL,
	numero_caixa int4 NULL,
	data_abertura varchar(6) NULL,
	qtde_pecas_conferidas int4 NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.daparelho (
	pk_aparelho varchar(6) NULL,
	desc_aparelho varchar(50) NULL,
	obs_aparelho varchar(100) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dcanaldistribuicao (
	id int4 NULL,
	descricao varchar(100) NULL,
	modalidade varchar(50) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dcentro_custo (
	cd_centro_custo int4 NULL,
	desc_centro_custo varchar(25) NULL,
	cd_desc varchar(70) NULL,
	cd_local_entrega int4 NULL,
	cd_tipo_mao_obra int2 NULL,
	cd_centro_custo_pai int8 NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dcontas_estoque (
	pk_conta_estoque int2 NULL,
	desc_conta_estoque varchar(40) NULL,
	tipo_produto_sped int2 NULL,
	itens_estoque int2 NULL,
	dthora_atualizacao timestamp NULL,
	tipo_conta_estoque int2 NULL
);

CREATE TABLE jma.ddeposito (
	codigo_deposito int2 NULL,
	descricao varchar(30) NULL,
	local_deposito int2 NULL,
	cod_desc_deposito varchar(50) NULL,
	hora_atualizacao timestamp NULL
);

CREATE TABLE jma.dfamilia_materiais (
	pk_familia int4 NULL,
	desc_familia varchar(25) NULL,
	desc_usuario_comprador varchar(250) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dfuncionariosinteg (
	cod_vendedor int4 NULL,
	cpf_vendedor varchar(20) NULL,
	nome_vendedor varchar(100) NULL,
	cargo varchar(100) NULL,
	loja varchar(20) NULL,
	cnpj varchar(40) NULL,
	status varchar(10) NULL,
	data_admissao timestamp NULL,
	data_demissao timestamp NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.dgrupo_contas (
	tipo_grupo_contas int2 NULL,
	desc_grupo_contas varchar(60) NULL,
	dthora_atualizacao timestamp NULL,
	pk_grupo_contas int4 NULL,
	obs varchar(300) NULL,
	observacao_grupo_contas varchar(100) NULL
);

CREATE TABLE jma.dhistorico_contabil (
	pk_historico numeric(4) NULL,
	desc_historico text NULL,
	flag_considera_regime text NULL,
	sinal_titulo numeric(1) NULL,
	sinal_diario numeric(1) NULL,
	sinal_comissao numeric(1) NULL,
	flag_entrada_saida text NULL,
	tipo_historico text NULL,
	flag_atualiza_comissao numeric(1) NULL,
	flag_atualiza_acc numeric(1) NULL,
	inf_custo numeric(1) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dmotivo_bloqueio (
	cod_bloqueio numeric(3) NULL,
	descricao varchar(200) NULL,
	flag_bloqueio numeric(1) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.dmotivo_cancelamento (
	cod_canc_pedido numeric(3) NULL,
	desc_canc_pedido varchar(200) NULL,
	tp_cancelamento numeric(1) NULL,
	grupo_canc_ped numeric(3) NULL
);

CREATE TABLE jma.dnatureza_operacao (
	pk_natureza int4 NULL,
	venda int2 NULL,
	devolucao int2 NULL,
	ranking int2 NULL,
	franchising int2 NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dparadasmaquinas_marft (
	"DATA" timestamp NULL,
	hora_inicio timestamp NULL,
	hora_fim timestamp NULL,
	minutos int4 NULL,
	codigo_motivo int2 NULL,
	motivo varchar(40) NULL,
	detalhes varchar(150) NULL,
	codigo_celula int4 NULL,
	nome_celula varchar(25) NULL,
	turno int2 NULL,
	ultima_atualizacao timestamp NULL,
	cod_operador int4 NULL,
	nome_operador varchar(50) NULL
);

CREATE TABLE jma.dperiodo_producao (
	data_ini_periodo timestamp NULL,
	data_fim_periodo timestamp NULL,
	dias_uteis int4 NULL,
	cd_area_periodo int2 NULL,
	desc_situacao_periodo int2 NULL,
	dthora_atualizacao timestamp NULL,
	cd_periodo_producao int4 NULL,
	pk_periodo_producao varchar(85) NULL,
	cd_empresa int4 NULL,
	cd_deposito int4 NULL,
	data_ini_fatu timestamp NULL,
	data_fim_fatu timestamp NULL,
	descricao varchar(20) NULL
);

CREATE TABLE jma.dprodutoproducao (
	pk_produto varchar(25) NULL,
	pk_produto_cigam varchar(14) NULL,
	cd_produto varchar(16) NULL,
	cd_desc_prod varchar(80) NULL,
	nivel_estrutura int2 NULL,
	desc_nivel_estrutura varchar(30) NULL,
	cd_referencia varchar(5) NULL,
	desc_produto varchar(70) NULL,
	und_medida varchar(2) NULL,
	desc_unidade_medida varchar(20) NULL,
	nm_tamanho varchar(15) NULL,
	nm_cor varchar(25) NULL,
	cd_colecao int2 NULL,
	desc_colecao varchar(30) NULL,
	cod_linha text NULL,
	linha_produto varchar(40) NULL,
	cod_artigo int2 NULL,
	desc_artigo varchar(30) NULL,
	artigos_cotas int2 NULL,
	desc_artigo_cotas varchar(30) NULL,
	cd_desc_referencia varchar(50) NULL,
	cod_desc_artigo varchar(50) NULL,
	cod_agrupador int2 NULL,
	desc_agrupador varchar(50) NULL,
	tipo_produto varchar(15) NULL,
	marca varchar(50) NULL,
	cd_conta_estoque int2 NULL,
	desc_conta_estoque varchar(50) NULL,
	desc_produto_narrativa varchar(90) NULL,
	cd_cor varchar(6) NULL,
	cd_tamanho varchar(5) NULL,
	desc_narrativa varchar(70) NULL,
	item_ativo int2 NULL,
	desc_referencia varchar(40) NULL,
	desc_segmento varchar(60) NULL,
	publico_alvo varchar(60) NULL,
	faixa_etaria varchar(60) NULL,
	codigo_contabil int4 NULL,
	classific_fiscal varchar(15) NULL,
	descr_class_fisc varchar(40) NULL,
	serie_tamanho int2 NULL,
	desc_serie_tamanho varchar(10) NULL,
	obs_serie_tamanho varchar(60) NULL,
	sub_colecao varchar(20) NULL,
	familia1 varchar(80) NULL,
	familia2 varchar(80) NULL,
	familia3 varchar(80) NULL,
	familia4 varchar(80) NULL,
	familia5 varchar(80) NULL,
	dthora_atualizacao timestamp NULL,
	alternativa_item int8 NULL,
	preco_custo numeric(18, 3) NULL
);

CREATE TABLE jma.dsituacao_venda (
	situacao_venda numeric(2) NULL,
	ultima_atualizacao timestamp NULL,
	descricao_situacao varchar(100) NULL
);

CREATE TABLE jma.dsituacaopedido (
	cod_situacao_venda varchar(2) NULL,
	desc_situacao_venda varchar(70) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.dstatus_pedido (
	status_pedido numeric(1) NULL,
	ultima_atualizacao timestamp NULL,
	descricao_status_pedido varchar(100) NULL
);

CREATE TABLE jma.dtabelapreco (
	col_tabela_preco int2 NULL,
	mes_tabela_preco int2 NULL,
	seq_tabela_preco int2 NULL,
	data_inicio_tabela timestamp NULL,
	data_fim_tabela timestamp NULL,
	descricao varchar(20) NULL,
	cod_desc_tabela_preco varchar(34) NULL,
	tabela_preco int4 NULL,
	tabela_preco_cod varchar(11) NULL,
	desc_catalogo varchar(40) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.fconfer_caixas (
	codigo_transferencia varchar(18) NULL,
	numero_caixa int4 NULL,
	qtde_pecas_conferidas int4 NULL,
	ultima_atualizacao timestamp NULL,
	data_abertura timestamp NULL
);

CREATE TABLE jma.fconfer_pecas_caixa (
	tipo varchar(13) NULL,
	codigo_transferencia varchar(18) NULL,
	numero_caixa int4 NULL,
	codigo_barras varchar(16) NULL,
	produto varchar(65) NULL,
	data_bipagem timestamp NULL,
	data_bipagem_recebido timestamp NULL,
	situacao varchar(8) NULL,
	ultima_atualizacao timestamp NULL,
	sku varchar(80) NULL
);

CREATE TABLE jma.fconsignadainteg (
	cd_loja varchar(6) NULL,
	dt_retirada timestamp NULL,
	dt_devol timestamp NULL,
	cd_status_devol varchar(8) NULL,
	qtd_consignada int4 NULL,
	vlr_preco_venda numeric(20, 4) NULL,
	vlr_perc_desconto numeric(20, 4) NULL,
	vlr_total numeric(20, 4) NULL,
	cd_vendido varchar(8) NULL,
	dthora_atualizacao timestamp NULL,
	cd_contr int4 NULL,
	dt_prev timestamp NULL,
	pk_consignado varchar(55) NULL,
	fk_produto varchar(20) NULL,
	cd_vendedor varchar(4) NULL,
	cd_loja_vendedor varchar(4) NULL,
	ds_cargo_vendedor varchar(100) NULL,
	status_vendedor varchar(10) NULL
);

CREATE TABLE jma.fcontrole_partes (
	descricao_parte varchar(30) NULL,
	parte_conjunto int2 NULL,
	qtde_parte_peca int2 NULL,
	tipo_corte_peca int2 NULL,
	tipo_enfesto_1 int2 NULL,
	tipo_enfesto_2 int2 NULL,
	alternativa_item int2 NULL,
	sequencia int2 NULL,
	alternativa_comp int2 NULL,
	estagio int4 NULL,
	qtde_camadas int4 NULL,
	centro_custo int4 NULL,
	inf_casado int2 NULL,
	grupo_estrutura varchar(5) NULL,
	inf_sentido int2 NULL,
	inf_casado_1 int2 NULL,
	inf_desenho int2 NULL,
	referencia varchar(111) NULL,
	componente varchar(111) NULL,
	comprimento_debrum numeric(10, 2) NULL,
	largura_debrum numeric(11, 3) NULL
);

CREATE TABLE jma.fdre_lojas (
	id int4 NULL,
	cnpj_loja varchar(18) NULL,
	apelido varchar(200) NULL,
	ano_dre int2 NULL,
	mes_dre int2 NULL,
	tipo_dre int2 NULL,
	propriedade varchar(150) NULL,
	val_real_ano_ant numeric(18, 3) NULL,
	perc_real_ano_ant numeric(18, 3) NULL,
	val_orcado numeric(18, 3) NULL,
	perc_orcado numeric(18, 3) NULL,
	val_real numeric(18, 3) NULL,
	perc_real numeric(18, 3) NULL,
	val_diferenca_orcado_real numeric(18, 3) NULL,
	perc_diferenca_orcado_real numeric(18, 3) NULL,
	perc_diferenca_real_vig_ant numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL,
	seq_consulta varchar(20) NULL
);

CREATE TABLE jma.fdre_orcado_lojas (
	id int4 NULL,
	seq_consulta varchar(50) NULL,
	cnpj_loja varchar(18) NULL,
	apelido varchar(200) NULL,
	ano_orcamento int2 NULL,
	mes_orcamento int2 NULL,
	propriedade varchar(150) NULL,
	tipo_orcamento int2 NULL,
	valor_orcado numeric(15, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.feficiencia_prod_marft (
	"DATA" timestamp NULL,
	maquina varchar(25) NULL,
	turno int2 NULL,
	min_dispo int4 NULL,
	operador int2 NULL,
	capacidade numeric(18, 3) NULL,
	minutos_trabalhado numeric(18, 3) NULL,
	minutos_produzido numeric(18, 3) NULL,
	eficiencia numeric(18, 3) NULL,
	perc_eficiencia numeric(18, 3) NULL,
	pecas_produzidas numeric(18, 3) NULL,
	minutos_parados numeric(18, 3) NULL,
	minutos_perdidos numeric(18, 3) NULL,
	real_eficiencia numeric(18, 3) NULL,
	perc_real_efic numeric(18, 3) NULL,
	perd_eficiencia numeric(18, 3) NULL,
	perc_perd_efic numeric(18, 3) NULL,
	parada numeric(18, 3) NULL,
	perc_parada numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL,
	capacidade_ajustada numeric(18, 3) NULL
);

CREATE TABLE jma.feficiencia_prod_operador_marft (
	"data" timestamp NULL,
	maquina text NULL,
	turno numeric(3) NULL,
	min_dispo numeric(5) NULL,
	operador numeric(3) NULL,
	codigo_operador numeric(5) NULL,
	nome_operador text NULL,
	capacidade numeric(10) NULL,
	minutos_trabalhado numeric(10) NULL,
	minutos_produzido numeric(8, 2) NULL,
	eficiencia numeric(6, 4) NULL,
	perc_eficiencia numeric(38, 10) NULL,
	pecas_produzidas numeric(10) NULL,
	minutos_parados numeric(10) NULL,
	minutos_perdidos numeric(10) NULL,
	real_eficiencia numeric(6, 4) NULL,
	perc_real_efic numeric(38, 10) NULL,
	perd_eficiencia numeric(6, 4) NULL,
	perc_perd_efic numeric(38, 10) NULL,
	parada numeric(5, 4) NULL,
	perc_parada numeric(38, 10) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.festrutura_produto (
	pk_produto varchar(18) NULL,
	cod_referencia varchar(5) NULL,
	cod_componente varchar(18) NULL,
	fk_sequencia int4 NULL,
	fk_estagio int4 NULL,
	consumo numeric(18, 3) NULL,
	qtd_camadas numeric(18, 3) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.ffaixas_comissao (
	tipo_info varchar(23) NULL,
	cod_loja float8 NULL,
	cargo float8 NULL,
	faixa float8 NULL,
	valor_inicio numeric(18, 3) NULL,
	valor_fim numeric(18, 3) NULL,
	percentual_inicio numeric(18, 3) NULL,
	percentual_fim numeric(18, 3) NULL,
	comissao numeric(18, 3) NULL,
	ultima_atualizao timestamp NULL
);

CREATE TABLE jma.ffaixas_comissao_omnichannel (
	cod_loja int4 NULL,
	faixa int2 NULL,
	comissao numeric(18, 3) NULL,
	tempo_medio int2 NULL,
	valor_atingido numeric(18, 3) NULL,
	valor_nao_atingido numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.ffaturamento (
	pk_cliente varchar(18) NULL,
	pk_produto varchar(18) NULL,
	nf_dataemissao timestamp NULL,
	nf_nrseqitempedido int2 NULL,
	data_embarque timestamp NULL,
	desc_nat_oper varchar(40) NULL,
	uf varchar(2) NULL,
	tipo_nota varchar(11) NULL,
	nf_notafiscal int4 NULL,
	nf_nrpedidovenda int4 NULL,
	nf_serienotafiscal varchar(4) NULL,
	nf_cdrep float8 NULL,
	ultima_atualizacao timestamp NULL,
	nf_origem int8 NULL,
	nf_tipo_1dev_0ven int2 NULL,
	nf_cdempresa float8 NULL,
	nf_condpgto int2 NULL,
	nf_cdcancelamento int2 NULL,
	cfop varchar(44) NULL,
	cod_devolucao numeric(40) NULL,
	itemnf_vlrunit numeric(18, 3) NULL,
	itemnf_vlrfat numeric(18, 3) NULL,
	itemnf_vlrrateio numeric(18, 3) NULL,
	itemnf_vlr_tot numeric(18, 3) NULL,
	valor_desconto numeric(18, 3) NULL,
	itemnf_vlripi numeric(18, 3) NULL,
	itemnf_vlricms numeric(18, 3) NULL,
	itemnf_vlricmsdiferido numeric(18, 3) NULL,
	itemnf_vlrpis numeric(18, 3) NULL,
	itemnf_vlrcofins numeric(18, 3) NULL,
	itemnf_pesoliquido numeric(18, 3) NULL,
	nf_cod_situacao int2 NULL,
	nf_desc_situacao varchar(11) NULL,
	emite_duplicata int2 NULL,
	faturamento int2 NULL,
	itemnf_vlr_contabil numeric(18, 3) NULL,
	data_transacao timestamp NULL,
	itemnf_qtdfaturada numeric(18, 3) NULL,
	nf_cod_natureza int8 NULL,
	itemnf_cod_natureza int8 NULL,
	natureza_venda varchar(3) NULL,
	codigo_deposito int8 NULL,
	cod_funcionario numeric(18, 3) NULL,
	vlr_desc_especial numeric(18, 3) NULL,
	itemnf_vlr_franchising numeric(21, 3) NULL,
	ped_vlr_desc_especial numeric(18, 3) NULL,
	pk_loja varchar(25) NULL,
	codigo_barras varchar(16) NULL
);

CREATE TABLE jma.ffaturamento_dev (
	pk_cliente varchar(17) NULL,
	pk_produto varchar(20) NULL,
	cd_barra varchar(18) NULL,
	nf_cdrep int4 NULL,
	nf_cdempresa int4 NULL,
	nf_notafiscal int4 NULL,
	nf_serienotafiscal varchar(3) NULL,
	nf_dataemissao varchar(10) NULL,
	nf_dtemissao timestamp NULL,
	nf_datadigitacao timestamp NULL,
	nf_condpgto int4 NULL,
	nf_cdcancelamento int4 NULL,
	nf_nrpedidovenda int4 NULL,
	nf_nrseqitempedido int4 NULL,
	nf_origem int4 NULL,
	nf_tipo_1dev_0ven int4 NULL,
	nf_cod_situacao int4 NULL,
	nf_cod_natureza int4 NULL,
	itemnf_cod_natureza int4 NULL,
	natureza_venda varchar(5) NULL,
	nf_desc_situacao varchar(12) NULL,
	data_embarque timestamp NULL,
	cod_funcionario int4 NULL,
	cfop varchar(12) NULL,
	desc_nat_oper varchar(50) NULL,
	uf varchar(5) NULL,
	cod_devolucao varchar(50) NULL,
	mot_devolucao varchar(40) NULL,
	emite_duplicata int2 NULL,
	faturamento int2 NULL,
	itemnf_qtdfaturada numeric(8, 2) NULL,
	itemnf_vlrunit numeric(10, 2) NULL,
	itemnf_vlrfat numeric(10, 2) NULL,
	itemnf_vlr_contabil numeric(10, 2) NULL,
	itemnf_vlrrateio numeric(12, 2) NULL,
	itemnf_vlr_tot numeric(12, 2) NULL,
	valor_desconto numeric(12, 2) NULL,
	itemnf_vlripi numeric(12, 2) NULL,
	itemnf_vlricms numeric(12, 2) NULL,
	itemnf_vlricmsdiferido numeric(12, 2) NULL,
	itemnf_vlrpis numeric(12, 2) NULL,
	itemnf_vlrcofins numeric(12, 2) NULL,
	itemnf_pesoliquido numeric(12, 2) NULL,
	itemnf_vlr_franchising numeric(12, 2) NULL,
	perc_desc_fran numeric(12, 2) NULL,
	tipo_nota varchar(15) NULL,
	ultima_atualizacao timestamp NULL,
	data_transacao varchar(15) NULL,
	codigo_deposito numeric(12, 2) NULL,
	canal varchar(100) NULL,
	modalidade varchar(50) NULL,
	live_dt_entr_original timestamp NULL,
	nf_formapgto int8 NULL
);

CREATE TABLE jma.ffaturamento_dev_inc (
	"PK_CLIENTE" text NULL,
	"PK_PRODUTO" text NULL,
	"CD_BARRA" text NULL,
	"NF_CDREP" numeric(38, 10) NULL,
	"NF_CDEMPRESA" numeric(38, 10) NULL,
	"NF_NOTAFISCAL" numeric(9) NULL,
	"NF_SERIENOTAFISCAL" text NULL,
	"NF_DATAEMISSAO" text NULL,
	"NF_DTEMISSAO" timestamp NULL,
	"NF_DATADIGITACAO" timestamp NULL,
	"NF_CONDPGTO" numeric(3) NULL,
	"NF_CDCANCELAMENTO" numeric(2) NULL,
	"NF_NRPEDIDOVENDA" numeric(9) NULL,
	"NF_NRSEQITEMPEDIDO" numeric(38, 10) NULL,
	"NF_ORIGEM" numeric(38, 10) NULL,
	"NF_TIPO_1DEV_0VEN" numeric(38, 10) NULL,
	"NF_COD_SITUACAO" numeric(38, 10) NULL,
	"NF_COD_NATUREZA" numeric(3) NULL,
	"ITEMNF_COD_NATUREZA" numeric(38, 10) NULL,
	"NATUREZA_VENDA" text NULL,
	"NF_DESC_SITUACAO" text NULL,
	"DATA_EMBARQUE" timestamp NULL,
	"COD_FUNCIONARIO" numeric(38, 10) NULL,
	"CFOP" text NULL,
	"DESC_NAT_OPER" text NULL,
	"UF" text NULL,
	"COD_DEVOLUCAO" text NULL,
	"MOT_DEVOLUCAO" text NULL,
	"EMITE_DUPLICATA" numeric(1) NULL,
	"FATURAMENTO" numeric(1) NULL,
	"ITEMNF_QTDFATURADA" numeric(38, 10) NULL,
	"ITEMNF_VLRUNIT" numeric(38, 10) NULL,
	"ITEMNF_VLRFAT" numeric(38, 10) NULL,
	"ITEMNF_VLR_CONTABIL" numeric(38, 10) NULL,
	"ITEMNF_VLRRATEIO" numeric(15, 2) NULL,
	"ITEMNF_VLR_TOT" numeric(38, 10) NULL,
	"VALOR_DESCONTO" numeric(38, 10) NULL,
	"ITEMNF_VLRIPI" numeric(15, 2) NULL,
	"ITEMNF_VLRICMS" numeric(15, 2) NULL,
	"ITEMNF_VLRICMSDIFERIDO" numeric(38, 10) NULL,
	"ITEMNF_VLRPIS" numeric(15, 2) NULL,
	"ITEMNF_VLRCOFINS" numeric(15, 2) NULL,
	"ITEMNF_PESOLIQUIDO" numeric(38, 10) NULL,
	"ITEMNF_VLR_FRANCHISING" numeric(38, 10) NULL,
	"PERC_DESC_FRAN" numeric(38, 10) NULL,
	"TIPO_NOTA" text NULL,
	"ULTIMA_ATUALIZACAO" timestamp NULL,
	"DATA_TRANSACAO" text NULL,
	"CODIGO_DEPOSITO" numeric(38, 10) NULL,
	"CANAL" text NULL,
	"MODALIDADE" text NULL,
	"LIVE_DT_ENTR_ORIGINAL" timestamp NULL
);

CREATE TABLE jma.ffaturamento_eua (
	mes varchar(6) NULL,
	loja varchar(20) NULL,
	"SUM(DADOS.QUANTIDADE)" int8 NULL,
	ano varchar(5) NULL,
	ultima_atualizacao timestamp NULL,
	mes_ano varchar(20) NULL,
	"SUM(DADOS.VALORDOLAR)" numeric(12, 2) NULL,
	"SUM(DADOS.VALORREAL)" numeric(12, 2) NULL
);

CREATE TABLE jma.ffaturamento_internacional (
	pk_loja_internacional int4 NULL,
	qtd_faturado int2 NULL,
	tickets int2 NULL,
	dthora_atualizacao timestamp NULL,
	desc_loja varchar(40) NULL,
	valor_dolar numeric(18, 3) NULL,
	valor_real numeric(18, 3) NULL,
	data_fat timestamp NULL
);

CREATE TABLE jma.ffaturamento_nacional (
	tipo_faturamento varchar(20) NULL,
	exercicio int4 NULL,
	data_lancto timestamp NULL,
	cod_empresa int4 NULL,
	desc_empresa varchar(50) NULL,
	conta_contabil varchar(25) NULL,
	conta_reduzida int4 NULL,
	chave int4 NULL,
	seqchave int4 NULL,
	complemento_historico varchar(100) NULL,
	desc_plano_conta varchar(60) NULL,
	ultima_atualizacao timestamp NULL,
	canal_distr varchar(16) NULL,
	credito numeric(12, 2) NULL
);

CREATE TABLE jma.fhists_mov_ (
	periodo numeric(4) NULL,
	ordem_producao numeric(9) NULL,
	ordem_confeccao numeric(5) NULL,
	sequencia numeric(5) NULL,
	nivel text NULL,
	grupo text NULL,
	subgrupo text NULL,
	item text NULL,
	data_hora timestamp NULL,
	tipo text NULL,
	usuario text NULL,
	endereco text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.finspecao_qualidade (
	data_inspecao timestamp NULL,
	id_inspecao numeric(9) NULL,
	ordem_producao numeric(9) NULL,
	ordem_confeccao numeric(5) NULL,
	periodo numeric(4) NULL,
	turno numeric(1) NULL,
	cod_estagio numeric(5) NULL,
	inspetor text NULL,
	pk_produto text NULL,
	grupo_maq_estamp text NULL,
	subgrupo_maq_estamp text NULL,
	revisor_origem text NULL,
	qtde_inspecionar_pcs numeric(6) NULL,
	perc_inspecionar_pcs numeric(3) NULL,
	qtde_inspecionada_pcs numeric(6) NULL,
	qtde_rejeitada_pcs numeric(6) NULL,
	perc_rejeitada_pcs numeric(3) NULL,
	tipo_inspecao numeric(1) NULL,
	id_lancamento numeric(9) NULL,
	cod_estagio_defeito numeric(5) NULL,
	cod_motivo numeric(3) NULL,
	motivo text NULL,
	qtd_inspecao numeric(6) NULL,
	cod_chave_inspecao_medidas numeric(9) NULL,
	cod_chave_inspecao numeric(9) NULL,
	cod_chave_lancamento numeric(9) NULL,
	tip_medida numeric(2) NULL,
	seq_inspecao numeric(3) NULL,
	des_inspecao text NULL,
	val_medida_padrao numeric(7, 3) NULL,
	val_medida_real numeric(7, 3) NULL,
	val_toler_minima numeric(6, 2) NULL,
	val_toler_maxima numeric(6, 2) NULL,
	val_variacao numeric(7, 3) NULL,
	cod_usuario text NULL,
	dat_hor_inspecao timestamp NULL,
	data_atualizacao timestamp NULL
);

CREATE TABLE jma.flog_itens_transfer (
	cd_pedido int4 NULL,
	cd_pedido_cliente varchar(60) NULL,
	seq_item_pedido int4 NULL,
	cd_item_trans varchar(60) NULL,
	cd_destino_venda int4 NULL,
	cd_destino_cliente varchar(60) NULL,
	seq_item_destino int4 NULL,
	controle int2 NULL,
	dt_hora_insercao timestamp NULL,
	dthora_atualizacao timestamp NULL,
	cod_cancelamento int2 NULL,
	desc_canc_pedido varchar(20) NULL,
	qtd_transferida numeric(18, 3) NULL
);

CREATE TABLE jma.flogpedidos (
	cd_pedido int4 NULL,
	data_alteracao timestamp NULL,
	usuario_alteracao varchar(60) NULL,
	data_embarque_old timestamp NULL,
	data_embarque_new timestamp NULL,
	dthora_atualizacao timestamp NULL,
	qtd_total_old numeric(18, 3) NULL,
	qtd_total_new numeric(18, 3) NULL,
	desconto1_old numeric(18, 3) NULL,
	desconto1_new numeric(18, 3) NULL,
	desconto2_old numeric(18, 3) NULL,
	desconto2_new numeric(18, 3) NULL,
	desconto3_old numeric(18, 3) NULL,
	desconto3_new numeric(18, 3) NULL,
	vlr_liq_itens_old numeric(18, 3) NULL,
	vlr_liq_itens_new numeric(18, 3) NULL,
	vlr_liq_pedido_old numeric(18, 3) NULL,
	vlr_liq_pedido_new numeric(18, 3) NULL
);

CREATE TABLE jma.fmeta_diario_loja (
	pk_meta_dia varchar(20) NULL,
	cod_loja int4 NULL,
	ano int2 NULL,
	mes int2 NULL,
	dia int2 NULL,
	mes_ano varchar(81) NULL,
	qtd_meta int4 NULL,
	valor_meta numeric(18, 3) NULL,
	dthora_atualizacao timestamp NULL,
	dt_meta timestamp NULL
);

CREATE TABLE jma.fmeta_loja (
	pk_id_meta varchar(35) NULL,
	cd_loja int8 NULL,
	ano int8 NULL,
	mes int4 NULL,
	mes_ano varchar(86) NULL,
	qtd_meta int8 NULL,
	dthora_atualizacao timestamp NULL,
	vlr_meta numeric(17, 2) NULL
);

CREATE TABLE jma.fmeta_mensal_loja (
	mes_ano varchar(8) NULL,
	pk_meta_mes varchar(20) NULL,
	dthora_atualizacao timestamp NULL,
	cod_loja int4 NULL,
	ano int2 NULL,
	mes int2 NULL,
	qtd_meta int4 NULL,
	valor_meta numeric(18, 3) NULL
);

CREATE TABLE jma.fmeta_semanal_loja (
	pk_meta_dia varchar(20) NULL,
	cod_loja int4 NULL,
	ano int2 NULL,
	mes int2 NULL,
	mes_ano varchar(20) NULL,
	valor_meta numeric(18, 3) NULL,
	dthora_atualizacao timestamp NULL,
	dt_meta timestamp NULL,
	dt_inicio timestamp NULL,
	dt_fim timestamp NULL,
	semana int2 NULL
);

CREATE TABLE jma.fmetasestacoes (
	cod_estacao varchar(9) NULL,
	descricao_estacao varchar(150) NULL,
	cod_representante varchar(6) NULL,
	descricao_rep varchar(100) NULL,
	tipo_meta varchar(3) NULL,
	mes varchar(2) NULL,
	ano varchar(4) NULL,
	cod_agrupador varchar(9) NULL,
	descricao varchar(50) NULL,
	colecao varchar(3) NULL,
	ultima_atualizacao timestamp NULL,
	valor_meta numeric(18, 3) NULL,
	perc_distribuicao numeric(18, 3) NULL,
	calc_meta numeric(18, 3) NULL
);

CREATE TABLE jma.fmetasorcamento (
	tipo_meta varchar(1) NULL,
	desc_meta varchar(50) NULL,
	modalidade varchar(50) NULL,
	ano varchar(4) NULL,
	mes_venda varchar(9) NULL,
	ultima_atualizacao timestamp NULL,
	total numeric(18, 3) NULL,
	mes_ano varchar(15) NULL
);

CREATE TABLE jma.fmonitor_producao (
	cod_operador int2 NULL,
	nome_operador varchar(40) NULL,
	min_trab numeric(18, 3) NULL,
	min_prod numeric(18, 3) NULL,
	efic numeric(18, 3) NULL,
	status varchar(7) NULL,
	celula_destino varchar(25) NULL,
	celula_origem varchar(25) NULL
);

CREATE TABLE jma.fmovimentacoesestoque (
	cd_deposito int2 NULL,
	cd_nivel_estrutura varchar(20) NULL,
	fk_produto varchar(20) NULL,
	codigo_transacao int2 NULL,
	dt_movimentacao timestamp NULL,
	tipo_movimento varchar(3) NULL,
	qtd_movimento numeric(18, 3) NULL,
	qtd_saldo_fisico numeric(18, 3) NULL,
	vlr_movimento_unitario numeric(18, 3) NULL,
	vlr_saldo_financeiro numeric(18, 3) NULL,
	flag_periodo varchar(15) NULL,
	ultima_atualizacao timestamp NULL,
	cod_empresa int8 NULL,
	nome_empresa varchar(60) NULL,
	referencia varchar(20) NULL,
	tamanho varchar(20) NULL,
	cor varchar(20) NULL
);

CREATE TABLE jma.fmovimentos_loja (
	cod_empresa int4 NULL,
	fk_cliente_fornec varchar(23) NULL,
	fk_vendedor varchar(35) NULL,
	fk_produto varchar(41) NULL,
	cod_transacao int4 NULL,
	cod_usuario int4 NULL,
	cod_documento int4 NULL,
	cnpj varchar(14) NULL,
	cod_portal int4 NULL,
	dt_documento timestamp NULL,
	dt_lancamento timestamp NULL,
	serie varchar(10) NULL,
	qtd_movimento int8 NULL,
	forma_pagamento varchar(22) NULL,
	flag_cancelado varchar(1) NULL,
	flag_excluido varchar(1) NULL,
	desc_deposito varchar(100) NULL,
	natureza_operacao varchar(100) NULL,
	tabela_preco varchar(50) NULL,
	dthora_atualizacao timestamp NULL,
	cod_vale_troca varchar(9) NULL,
	motivo_troca varchar(60) NULL,
	valor_cofins numeric(15, 3) NULL,
	cfop varchar(5) NULL,
	operacao varchar(2) NULL,
	tipo_transacao varchar(1) NULL,
	num_vale varchar(200) NULL,
	fk_loja varchar(23) NULL,
	fk_loja_cigam varchar(40) NULL,
	cod_referencia varchar(20) NULL,
	tamanho varchar(50) NULL,
	desc_cor varchar(30) NULL,
	fk_produto_comercial varchar(102) NULL,
	identificador varchar(38) NULL,
	codigo_cliente int4 NULL,
	cod_vendedor int4 NULL,
	portal int4 NULL,
	loja varchar(50) NULL,
	pk_cigam_loja varchar(15) NULL,
	cnpj_original varchar(14) NULL,
	preco_custo numeric(18, 3) NULL,
	valor_liquido numeric(18, 3) NULL,
	valor_desconto numeric(18, 3) NULL,
	valor_icms numeric(18, 3) NULL,
	base_icms numeric(18, 3) NULL,
	valor_pis numeric(18, 3) NULL,
	base_pis numeric(18, 3) NULL,
	base_cofins numeric(18, 3) NULL,
	valor_ipi numeric(18, 3) NULL,
	base_ipi numeric(18, 3) NULL,
	valor_total numeric(18, 3) NULL,
	valor_frete numeric(18, 3) NULL,
	valor_preco_unitario numeric(18, 3) NULL,
	valor_vale_troca numeric(18, 3) NULL
);

CREATE TABLE jma.fmovimentosinteg (
	portal int8 NULL,
	fk_cliente varchar(40) NULL,
	numorcamento int8 NULL,
	usuario int8 NULL,
	numnf int8 NULL,
	serie varchar(10) NULL,
	chave_nf varchar(100) NULL,
	fk_produto varchar(25) NULL,
	hora_lancamento varchar(20) NULL,
	codigo_cliente int8 NULL,
	doc_cliente varchar(20) NULL,
	id_cfop varchar(20) NULL,
	cod_vendedor int8 NULL,
	operacao varchar(10) NULL,
	tipo_transacao varchar(10) NULL,
	cancelado varchar(3) NULL,
	seqitem int4 NULL,
	ultima_atualizacao timestamp NULL,
	cnpj varchar(40) NULL,
	valor_bruto int8 NULL,
	cor varchar(6) NULL,
	tamanho varchar(5) NULL,
	considerarvenda varchar(1) NULL,
	desc_movimento varchar(255) NULL,
	descricao varchar(200) NULL,
	rede varchar(100) NULL,
	canal_distribuicao varchar(14) NULL,
	flag_movimentacao varchar(20) NULL,
	cst_icms varchar(15) NULL,
	cst_ipi varchar(15) NULL,
	cst_cofins varchar(15) NULL,
	cst_pis varchar(15) NULL,
	desconto numeric(18, 3) NULL,
	preco_custo numeric(18, 3) NULL,
	valor_icms numeric(18, 3) NULL,
	aliquota_icms numeric(18, 3) NULL,
	base_icms numeric(18, 3) NULL,
	valor_ipi numeric(18, 3) NULL,
	aliquota_ipi numeric(18, 3) NULL,
	base_ipi numeric(18, 3) NULL,
	valor_cofins numeric(18, 3) NULL,
	aliquota_cofins numeric(18, 3) NULL,
	base_cofins numeric(18, 3) NULL,
	valor_pis numeric(18, 3) NULL,
	aliquota_pis numeric(18, 3) NULL,
	base_pis numeric(18, 3) NULL,
	valor_liquido numeric(18, 3) NULL,
	qtde numeric(18, 3) NULL,
	data_lancamento timestamp NULL,
	datcancel timestamp NULL,
	cod_barra varchar(20) NULL,
	data_inicio_vigencia date NULL,
	data_fim_vigencia date NULL,
	cnpj_original varchar(40) NULL,
	cnpj_antigo varchar(18) NULL,
	de varchar(20) NULL,
	para varchar(20) NULL,
	loja_original varchar(30) NULL,
	situacao int2 NULL,
	identificador varchar(60) NULL,
	cnpj_emp varchar(20) NULL,
	loja varchar(5) NULL
);

CREATE TABLE jma.fmovimentoslojamicrovix (
	cod_empresa int4 NULL,
	cod_transacao int4 NULL,
	rede varchar(50) NULL,
	desc_apelido varchar(200) NULL,
	data_lancamento timestamp NULL,
	id_cfop varchar(5) NULL,
	operacao varchar(2) NULL,
	desc_operacao varchar(200) NULL,
	numnf int4 NULL,
	loja varchar(100) NULL,
	cnpj_emp varchar(100) NULL,
	tipo_transacao varchar(1) NULL,
	transacao varchar(100) NULL,
	canal_distribuicao varchar(100) NULL,
	valorvendas numeric(18, 3) NULL,
	qtdepedidos numeric(18, 3) NULL,
	qtdedevolucao numeric(18, 3) NULL,
	qtdeitensvendida numeric(18, 3) NULL,
	valordesconto numeric(18, 3) NULL
);

CREATE TABLE jma.fordens_corte_congelado (
	estagio int4 NULL,
	data_programacao timestamp NULL,
	simultaneo int4 NULL,
	op int4 NULL,
	oc int4 NULL,
	periodo int2 NULL,
	referencia text NULL,
	cor text NULL,
	prioridade int4 NULL,
	cor_prioridade text NULL,
	qtd_produzir numeric(18, 3) NULL,
	qtd_ajustada numeric(38, 18) NULL,
	tempo_produzir numeric(18, 3) NULL,
	tempo_costura numeric(38, 18) NULL,
	data_producao timestamp NULL,
	data_congelamento date NULL,
	data_entrada_estagio timestamp NULL
);

CREATE TABLE jma.fparametro_compra (
	cod_empresa numeric(3) NULL,
	fk_produto text NULL,
	fk_familia_materiais numeric(5) NULL,
	estoque_minimo numeric(13, 3) NULL,
	estoque_maximo numeric(13, 3) NULL,
	tempo_reposicao numeric(5) NULL,
	lote_multiplo numeric(13, 3) NULL,
	cod_deposito numeric(3) NULL,
	bloqueia_compra numeric(1) NULL,
	dthora_atualizacao timestamp NULL,
	lote_minimo numeric(16, 3) NULL
);

CREATE TABLE jma.fpedido_congelado (
	pedido_venda int4 NULL,
	data_entr_venda timestamp NULL,
	situacao_venda int2 NULL,
	cod_cancelamento int2 NULL,
	sit_aloc_pedi int2 NULL,
	sit_coletor int2 NULL,
	situacao_coleta int2 NULL,
	status_expedicao int2 NULL,
	status_homologacao int2 NULL,
	status_pedido int2 NULL,
	status_comercial int2 NULL,
	sit_conferencia int2 NULL,
	data_congelamento timestamp NULL,
	qtde_saldo_pedi numeric(18, 3) NULL,
	valor_saldo_pedi numeric(18, 3) NULL
);

CREATE TABLE jma.fpedidos_compra (
	ped_compra numeric(8) NULL,
	itemped_seq_ped numeric(4) NULL,
	obs_pedido varchar(300) NULL,
	dt_emissao_compra timestamp NULL,
	dt_prev_entrega timestamp NULL,
	fk_cond_pgto numeric(3) NULL,
	ped_vendedor varchar(60) NULL,
	fk_comprador numeric(5) NULL,
	fk_grupo_contas numeric(5) NULL,
	fk_familia numeric(8) NULL,
	itemped_qtd_pedida numeric(15, 3) NULL,
	itemped_qtd_saldo numeric(15, 3) NULL,
	itemped_qtd_recebida numeric(15, 3) NULL,
	itemped_situacao_item varchar(13) NULL,
	itemped_preco numeric(15, 5) NULL,
	itemped_percentual_desc numeric(8, 2) NULL,
	itemped_percentual_ipi numeric(8, 2) NULL,
	itemped_centro_custo numeric(8) NULL,
	itemped_cod_cancelamento numeric(4) NULL,
	dt_cancelamento timestamp NULL,
	itemped_requisicao numeric(8) NULL,
	dthora_atualizacao timestamp NULL,
	fk_produto varchar(30) NULL,
	fk_fornecedor varchar(18) NULL,
	fk_conta_estoque varchar(5) NULL,
	codigo_contabil int4 NULL
);

CREATE TABLE jma.fpedidos_embarque_previsto (
	pedido_venda numeric(9) NULL,
	data_entr_venda timestamp NULL,
	situacao_venda numeric(2) NULL,
	cod_cancelamento numeric(3) NULL,
	sit_aloc_pedi numeric(1) NULL,
	sit_coletor numeric(1) NULL,
	situacao_coleta numeric(1) NULL,
	status_expedicao numeric(1) NULL,
	status_homologacao numeric(1) NULL,
	status_pedido numeric(1) NULL,
	status_comercial numeric(1) NULL,
	sit_conferencia numeric(1) NULL,
	qtde_saldo_pedi numeric(15, 3) NULL,
	qtde_pedida numeric(15, 3) NULL,
	qtde_afaturar numeric(15, 3) NULL,
	val_liq_unt numeric(15, 3) NULL,
	valor_unitario numeric(15, 3) NULL,
	ultima_atualizacao date NULL,
	cnpj_cliente varchar(35) NULL,
	codigo_deposito int2 NULL,
	seq_item_pedido int2 NULL,
	fk_produto varchar(35) NULL,
	natureza_venda varchar(10) NULL,
	canal varchar(100) NULL,
	qtde_faturada numeric(18, 3) NULL,
	valor_saldo_pedi numeric(18, 3) NULL
);

CREATE TABLE jma.fpedidos_url (
	"data" varchar(20) NULL,
	hora varchar(10) NULL,
	id_pedido int8 NULL,
	cliente varchar(150) NULL,
	id_vendedor int8 NULL,
	cpf_vendedor varchar(20) NULL,
	grupo_vendedor varchar(50) NULL,
	cnpj varchar(20) NULL,
	url_loja varchar(100) NULL,
	numero_nf varchar(20) NULL,
	serie_nf varchar(10) NULL,
	omnichannel varchar(10) NULL,
	ultima_atualizacao timestamp NULL,
	tipo varchar(30) NULL,
	cupom varchar(40) NULL,
	desconto_cupom varchar(40) NULL,
	codigo_vendedor varchar(40) NULL,
	desconto_vendedor varchar(40) NULL,
	status varchar(80) NULL,
	total_liquido numeric(18, 3) NULL,
	total_desconto numeric(18, 3) NULL,
	total_bruto numeric(18, 3) NULL,
	pagamento varchar(80) NULL,
	vendedor varchar(80) NULL
);

CREATE TABLE jma.fportal_lojas (
	cn_id int8 NULL,
	cn_num_nota_fiscal int4 NULL,
	cn_inicio_conferencia_volumes timestamp NULL,
	cn_ultima_leitura_volumes timestamp NULL,
	cn_ultima_leitura_tags timestamp NULL,
	cn_status_volumes int2 NULL,
	cn_desc_status_volumes varchar(14) NULL,
	tcv_id int8 NULL,
	tcv_numero_volume int4 NULL,
	tcv_inicio_conferencia timestamp NULL,
	tcv_ultima_leitura timestamp NULL,
	tcv_status_pecas int2 NULL,
	tcv_desc_status_pecas varchar(14) NULL,
	ct_id int8 NULL,
	ct_data_bip timestamp NULL,
	ct_usuario varchar(55) NULL,
	ct_status int2 NULL,
	ct_pk_produto varchar(18) NULL,
	ct_desc_status varchar(14) NULL,
	cv_id int8 NULL,
	cv_data_bip timestamp NULL,
	cv_status int2 NULL,
	cv_desc_status varchar(14) NULL,
	ra_id int8 NULL,
	ra_cnpj varchar(17) NULL,
	ra_usuario_bipou varchar(55) NULL,
	ra_nome_usuario varchar(55) NULL,
	ra_tipo int2 NULL,
	ra_status int2 NULL,
	ra_codigo_bipado varchar(100) NULL,
	ra_acao varchar(2500) NULL,
	ra_data_bipagem timestamp NULL,
	ra_codigo_empresa int2 NULL,
	ra_serie_nota_fisc varchar(3) NULL,
	ra_desc_status varchar(14) NULL,
	usu_id int8 NULL,
	usu_nome varchar(55) NULL,
	usu_usuario varchar(55) NULL,
	usu_situacao int2 NULL,
	usu_cnpj varchar(18) NULL,
	ct_numero_tag varchar(60) NULL,
	tcv_tags_conferidas numeric(18, 3) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE jma.fprioridade_beneficiamento_conge (
	prioridade numeric(3) NULL,
	work_order_id text NULL,
	work_center text NULL,
	planta text NULL,
	cliente text NULL,
	quantidade numeric(38, 10) NULL,
	sku text NULL,
	descricao_sku text NULL,
	tipo_wo text NULL,
	data_fim_periodo timestamp NULL,
	data_termino timestamp NULL,
	familia_produto text NULL,
	tamanho text NULL,
	cor text NULL,
	referencia text NULL,
	periodo_producao numeric(4) NULL,
	ordem_producao numeric(9) NULL,
	pk_maquina text NULL,
	pk_maquina_num text NULL,
	qtde_quilos_prog numeric(13, 3) NULL,
	qtde_rolos_prog numeric(10, 2) NULL,
	qtde_rolos_prod numeric(9, 3) NULL,
	qtde_rolos_prog_1 numeric(10, 3) NULL,
	qtde_rolos_real numeric(6, 3) NULL,
	qtde_quilos_prod numeric(9, 3) NULL,
	situacao text NULL,
	data_atualizacao timestamp NULL
);

CREATE TABLE jma.fprioridade_tecelagem_conge (
	prioridade numeric(9) NULL,
	work_order_id text NULL,
	work_center text NULL,
	planta text NULL,
	cliente text NULL,
	sku text NULL,
	descricao_sku text NULL,
	tipo_wo text NULL,
	data_fim_periodo timestamp NULL,
	data_termino timestamp NULL,
	familia_produto text NULL,
	tamanho text NULL,
	cor text NULL,
	referencia text NULL,
	alternativa_item numeric(2) NULL,
	roteiro_opcional numeric(2) NULL,
	numero_lote text NULL,
	opcao_maquina numeric(3) NULL,
	periodo_producao numeric(4) NULL,
	ordem_producao numeric(6) NULL,
	pk_maquina text NULL,
	pk_maquina_num text NULL,
	quantidade numeric(38, 10) NULL,
	qtde_quilos_prog numeric(12, 3) NULL,
	qtde_rolos_prog numeric(8, 1) NULL,
	peso_rolo numeric(8, 3) NULL,
	qtde_unidades_prog numeric(15, 3) NULL,
	qtde_rolos_prog_1 numeric(8, 1) NULL,
	qtde_rolos_prod numeric(8, 1) NULL,
	cod_cancelamento numeric(3) NULL,
	data_atualizacao timestamp NULL
);

CREATE TABLE jma.fprod_marft (
	op int4 NULL,
	os int4 NULL,
	tip_prod int2 NULL,
	hora timestamp NULL,
	seq int2 NULL,
	desc_prod varchar(50) NULL,
	referencia varchar(50) NULL,
	produto varchar(150) NULL,
	operacao varchar(80) NULL,
	operationcode varchar(20) NULL,
	tecido varchar(90) NULL,
	grupo varchar(70) NULL,
	"S.U." varchar(20) NULL,
	camada int2 NULL,
	tempo_total numeric(18, 3) NULL,
	tempo_peca numeric(18, 3) NULL,
	carga numeric(18, 3) NULL,
	oper int8 NULL,
	operador varchar(150) NULL,
	ultima_atualizacao timestamp NULL,
	"Data" timestamp NULL,
	temp_prep numeric(18, 3) NULL,
	temp_conclus numeric(18, 3) NULL,
	comp_total numeric(18, 3) NULL,
	tempo_tot_camada numeric(18, 3) NULL,
	tempo_camada numeric(18, 3) NULL,
	qtd_emenda numeric(18, 3) NULL,
	temp_emend numeric(18, 3) NULL,
	qtd_ton numeric(18, 3) NULL,
	tempo_ton numeric(18, 3) NULL,
	qtd_troca numeric(18, 3) NULL,
	tempo_troca_rolo numeric(18, 3) NULL
);

CREATE TABLE jma.freq_almoxarifado (
	num_requisicao numeric(6) NULL,
	ordem_producao numeric(9) NULL,
	ccusto_destino int4 NULL,
	data_requis timestamp NULL,
	requisitante varchar(50) NULL,
	situacao_capa varchar(32) NULL,
	referencia varchar(5) NULL,
	conta_estoque int2 NULL,
	pk_produto varchar(25) NULL,
	um varchar(2) NULL,
	deposito int2 NULL,
	observacao varchar(120) NULL,
	qtde_requisitada numeric(18, 3) NULL,
	a_receber numeric(18, 3) NULL,
	estoque numeric(18, 3) NULL,
	ult_compra numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL,
	situacao varchar(32) NULL,
	data_entregue timestamp NULL,
	codigo_transacao int2 NULL,
	usuario_receptor varchar(200) NULL,
	almoxarife varchar(20) NULL,
	sequencia int2 NULL
);

CREATE TABLE jma.frequisicoes_compra (
	num_requisicao numeric(6) NULL,
	seq_item_req numeric(2) NULL,
	codigo_deposito numeric(3) NULL,
	data_requisicao timestamp NULL,
	nome_requisit text NULL,
	observacao_req text NULL,
	data_prev_entr_req timestamp NULL,
	situacao_codigo numeric(1) NULL,
	situacao text NULL,
	pedido_compra numeric(6) NULL,
	data_prev_entr_ped timestamp NULL,
	fk_produto text NULL,
	fk_fornecedor text NULL,
	unidade_medida text NULL,
	qtde_requisitada numeric(15, 3) NULL,
	qtde_pedida_item numeric(15, 3) NULL,
	valor_unitario numeric(20, 5) NULL,
	ultimaentrada timestamp NULL,
	ultimasaida timestamp NULL,
	estoqueatual numeric(38, 10) NULL,
	qtdsugerida numeric(38, 10) NULL,
	precoultentrada numeric(38, 10) NULL,
	estoquemin numeric(38, 10) NULL,
	estoquemax numeric(38, 10) NULL,
	consumomedmes numeric(38, 10) NULL,
	consumopordia numeric(38, 10) NULL,
	ult_forn text NULL,
	ult_ped numeric(6) NULL,
	qtd_ult_ped numeric(38, 10) NULL,
	quantidade_nf numeric(38, 10) NULL,
	valor_total_nf numeric(38, 10) NULL
);

CREATE TABLE jma.froteiro (
	num_roteiro int2 NULL,
	seq_operacao int2 NULL,
	fk_operacao int4 NULL,
	fk_estagio int2 NULL,
	seq_estagio int2 NULL,
	estagio_depende int2 NULL,
	qtd_rolos int4 NULL,
	observacao_roteiro varchar(200) NULL,
	centro_custo int4 NULL,
	ccusto_homem int4 NULL,
	dthora_atualizacao timestamp NULL,
	qtd_cordas int4 NULL,
	minutos_roteiro numeric(18, 3) NULL,
	velocidade numeric(18, 3) NULL,
	minutos_homem numeric(18, 3) NULL,
	fk_produto varchar(20) NULL,
	alternativa_item int4 NULL
);

CREATE TABLE jma.froteiro_em_producao (
	fk_produto varchar(111) NULL,
	numero_alternati int2 NULL,
	numero_roteiro int2 NULL,
	seq_operacao int2 NULL,
	codigo_operacao int4 NULL,
	codigo_estagio int4 NULL,
	nr_agulhas int2 NULL,
	tempo_maquina numeric(18, 3) NULL,
	custo_homem int4 NULL,
	custo_minuto numeric(18, 3) NULL,
	tempo_homem numeric(18, 3) NULL,
	fk_maquina varchar(39) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE jma.ftabelapreco (
	dthora_atualizacao timestamp NULL,
	grupo_estrutura varchar(10) NULL,
	tabela_preco varchar(10) NULL,
	tabela_preco_cod varchar(10) NULL,
	fk_produto varchar(50) NULL,
	vlr_com_desconto numeric(18, 3) NULL,
	val_tabela_preco numeric(18, 3) NULL,
	tabela_preco_grupo numeric(25, 6) NULL
);

CREATE TABLE jma.ftempo_metodos (
	pk_produto varchar(111) NULL,
	alt int2 NULL,
	rot int2 NULL,
	sub_grupo varchar(3) NULL,
	codigo_estagio int4 NULL,
	codigo_operacao int4 NULL,
	pk_maquina varchar(39) NULL,
	agulhas varchar(3) NULL,
	custo_homem numeric(18, 3) NULL,
	ultima_atualizacao timestamp NULL,
	custo_minuto numeric(18, 3) NULL,
	tempo_homem varchar NULL,
	tempo_maquina varchar NULL
);

CREATE TABLE jma.ftitulos_receber (
	codigo_empresa numeric(3) NULL,
	num_duplicata numeric(9) NULL,
	seq_duplicatas numeric(2) NULL,
	cod_chave_nota text NULL,
	num_titulo text NULL,
	portador_duplic numeric(3) NULL,
	cod_rep_cliente numeric(5) NULL,
	data_emissao timestamp NULL,
	numero_remessa numeric(7) NULL,
	ind_previsao numeric(1) NULL,
	num_titulo_banco text NULL,
	num_pedido numeric(9) NULL,
	per_comiss numeric(6, 2) NULL,
	cod_motivo_cancel numeric(2) NULL,
	des_motivo_cancel text NULL,
	cod_forma_pagto numeric(2) NULL,
	dat_cancel timestamp NULL,
	dat_ult_pagto_aux timestamp NULL,
	cod_tipo_duplic numeric(2) NULL,
	des_tipo_duplic text NULL,
	des_cod_tipo_duplic text NULL,
	cod_posicao_duplic numeric(2) NULL,
	des_posicao_duplic text NULL,
	des_situa_duplic text NULL,
	des_situa_aberta_baixada text NULL,
	cod_situa_duplic numeric(1) NULL,
	cnpj_cliente text NULL,
	pk_cliente text NULL,
	cod_cidade numeric(5) NULL,
	dat_vencto_aux timestamp NULL,
	dat_vencto_original_aux timestamp NULL,
	sit_vencto text NULL,
	val_aberto numeric(15, 2) NULL,
	val_comiss numeric(15, 2) NULL,
	val_titulo numeric(15, 2) NULL,
	cod_conta_contabil numeric(6) NULL
);

CREATE TABLE jma.fvendas_url (
	id numeric(10) NULL,
	pedido numeric(9) NULL,
	nota_fiscal numeric(9) NULL,
	quantidade numeric(15, 3) NULL,
	valor_faturado numeric(15, 3) NULL,
	canal varchar(100) NULL,
	cnpj varchar(15) NULL,
	serie_nota_fiscal varchar(3) NULL,
	pedido_cliente varchar(30) NULL,
	"DATA" timestamp NULL,
	data_emissao timestamp NULL,
	cupom varchar(35) NULL,
	loja varchar(65) NULL,
	cpf_vendedor varchar(11) NULL,
	cnpj_loja varchar(15) NULL,
	ultima_atualizacao timestamp NULL,
	nota_entrada float8 NULL,
	nota_saida float8 NULL,
	motivo_devolucao varchar(400) NULL,
	flag_tipo varchar(3) NULL,
	tipo_cliente varchar(100) NULL,
	cliente varchar(100) NULL,
	tipo_cupom varchar(100) NULL,
	vendedor varchar(255) NULL,
	valor_comissao numeric(18, 3) NULL,
	grupo_loja varchar(100) NULL,
	tela varchar(10) NULL,
	omnichannel varchar(3) NULL,
	fornecedor varchar(55) NULL,
	percentual_comissao numeric(18, 3) NULL,
	valor_comissao_ktl numeric(18, 3) NULL
);

CREATE TABLE jma.ped_cong_motivo_bloqueio (
	pedido_venda int4 NULL,
	seq_situacao int2 NULL,
	codigo_situacao int2 NULL,
	flag_liberacao varchar(1) NULL,
	data_situacao timestamp NULL,
	data_liberacao timestamp NULL,
	data_congelamento timestamp NULL
);