-- Schema: live
-- Tabelas: 20

CREATE TABLE live.dbriefing (
	referencia varchar(6) NULL,
	cor_venda varchar(6) NULL,
	ref_cor varchar(11) NULL,
	desc_colecao varchar(60) NULL,
	desc_sub_colecao varchar(100) NULL,
	linha_produto varchar(40) NULL,
	desc_segmento varchar(62) NULL,
	pilar varchar(64) NULL,
	artigo_produto varchar(25) NULL,
	desc_comercial varchar(100) NULL,
	desc_tamanhos varchar(10) NULL,
	grade varchar(700) NULL,
	mp_principal varchar(20) NULL,
	mp_principal_desc varchar(30) NULL,
	num_sku int4 NULL,
	ultima_atualizacao timestamp NULL,
	ano_venda int4 NULL,
	modalidade varchar(68) NULL,
	classificacao_permanentes varchar(20) NULL,
	tipo_producao varchar(70) NULL,
	categoria_produto varchar(72) NULL,
	sub_categoria_produto varchar(74) NULL,
	comprimento_entrepernas varchar(76) NULL,
	tipo_shape varchar(78) NULL,
	comprimento varchar(80) NULL,
	tipo_alca varchar(82) NULL,
	tipo_decote varchar(62) NULL,
	tipo_gola varchar(64) NULL,
	tipo_manga varchar(86) NULL,
	tipo_sustentacao varchar(68) NULL,
	decoracoes varchar(78) NULL,
	tipo_estampa varchar(80) NULL,
	capacidade varchar(82) NULL,
	fat_plan_fabrica date NULL,
	lancamento_plan_loja date NULL,
	live_familia varchar(62) NULL,
	live_conjunto varchar(255) NULL,
	piramide varchar(60) NULL,
	cluster_comercial varchar(10) NULL,
	aposta_criacao numeric(1) NULL,
	estoque_limitado numeric(1) NULL,
	grade_multipla numeric(1) NULL,
	live_run numeric(1) NULL,
	acao_varejo numeric(1) NULL,
	must_have numeric(1) NULL,
	nova_cor numeric(1) NULL,
	visual_merchandising numeric(1) NULL,
	tamanho_vitrine varchar(1) NULL,
	promocional numeric(1) NULL,
	tecido varchar(60) NULL,
	colecao varchar(200) NULL,
	abreviacao_colecao varchar(100) NULL,
	sub_colecao varchar(100) NULL,
	linha varchar(100) NULL,
	familia varchar(50) NULL,
	segmento varchar(50) NULL,
	nomenclatura varchar(50) NULL,
	estilista varchar(50) NULL,
	assistente_estilo varchar(100) NULL,
	unidade_medida varchar(100) NULL,
	tipo_artigo varchar(200) NULL,
	artigo_cotas varchar(200) NULL,
	comprado_fabricado varchar(200) NULL,
	modalidades varchar(200) NULL,
	high_lights varchar(4000) NULL,
	stylist varchar(4000) NULL,
	dt_integracao timestamp NULL,
	informacoes_marketing varchar(4000) NULL,
	caract_produto_port varchar(4000) NULL,
	descr_com_port varchar(4000) NULL,
	caract_produto_ing varchar(4000) NULL,
	descr_com_ing varchar(4000) NULL,
	descr_com_ecommerce_ing varchar(4000) NULL,
	caract_produto_esp varchar(4000) NULL,
	descr_com_esp varchar(100) NULL,
	descr_com_ecommerce_esp varchar(4000) NULL,
	neon numeric(1) NULL,
	look_book numeric(1) NULL,
	icone_acron varchar(3) NULL,
	texto_portugues varchar(1000) NULL,
	texto_ingles varchar(1000) NULL,
	texto_espanhol varchar(1000) NULL,
	descricao_classificacao varchar(50) NULL,
	descricao_base_releitura varchar(50) NULL,
	rede_vendas_indicado varchar(50) NULL
);

CREATE TABLE live.dcad_centro_custo (
	centro_custo int4 NULL,
	descricao varchar(20) NULL,
	divisao_producao int2 NULL,
	custo_despesa int2 NULL,
	fixo_variavel int2 NULL,
	tipo_mao_obra int2 NULL,
	tipo_ccusto int2 NULL,
	situacao int2 NULL,
	tempo_turno1 int2 NULL,
	tempo_turno2 int2 NULL,
	tempo_turno3 int2 NULL,
	tempo_turno4 int2 NULL,
	local_entrega varchar(20) NULL,
	centro_custo_pai int4 NULL,
	data_alteracao timestamp NULL,
	validar_cc_empresa varchar(1) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE live.dcalendario (
	"data" date NULL,
	ano int4 NULL,
	mes int4 NULL,
	nummesano varchar(20) NULL,
	mes_ano varchar(20) NULL,
	nm_mes varchar(20) NULL,
	abrev_mes varchar(20) NULL,
	dia int4 NULL,
	nm_dia varchar(20) NULL,
	abrev_dia varchar(20) NULL,
	nr_dia_semana int4 NULL,
	numero_semana int4 NULL,
	semana_ano_tabela varchar(30) NULL,
	dia_do_ano int4 NULL,
	dia_semana int4 NULL,
	dia_util int4 NULL,
	dia_util_finan int4 NULL,
	ultima_atualizacao date NULL
);

CREATE TABLE live.dcanaldistribuicao (
	id int4 NULL,
	descricao varchar(100) NULL,
	modalidade varchar(50) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE live.dcidades (
	cod_cidade varchar(5) NULL,
	nm_cidade varchar(60) NULL,
	uf varchar(2) NULL,
	ddd int2 NULL,
	cod_pais int2 NULL,
	cod_fiscal int4 NULL,
	cod_reg_mer_ex int2 NULL,
	populacao int4 NULL,
	cod_cidade_zona_franca int4 NULL,
	cod_cidade_ibge int4 NULL,
	cod_sub_regiao int2 NULL,
	sub_regiao varchar(40) NULL,
	cod_suframa int2 NULL,
	cep int4 NULL,
	dthora_atualizacao timestamp NULL,
	nm_pais varchar(30) NULL,
	estado_extenso varchar(30) NULL
);

CREATE TABLE live.dcliente (
	pk_cliente varchar(16) NULL,
	cod_empresa int2 NULL,
	nm_cliente varchar(70) NULL,
	nm_fantasia varchar(70) NULL,
	fone_cliente int4 NULL,
	uf_cliente varchar(2) NULL,
	cep int4 NULL,
	cidade varchar(70) NULL,
	endereco varchar(70) NULL,
	bairro varchar(20) NULL,
	dt_cadastro timestamp NULL,
	cod_representante int2 NULL,
	nm_representante varchar(50) NULL,
	nm_subregiao_cliente varchar(20) NULL,
	tipo_cliente varchar(70) NULL,
	tipo_cliente_agrupamento varchar(60) NULL,
	dt_ult_compra timestamp NULL,
	vlr_ult_compra numeric(18, 3) NULL,
	prazo_medio numeric(9, 3) NULL,
	dt_ultima_fatura timestamp NULL,
	email_cliente varchar(100) NULL,
	grupo_economico varchar(60) NULL,
	cd_grupo_economico int4 NULL,
	situacao_cliente varchar(7) NULL,
	conceito_cliente varchar(20) NULL,
	modalidade_cliente varchar(30) NULL,
	pais_cliente varchar(25) NULL,
	regiao_cliente varchar(20) NULL,
	cod_cidade int4 NULL,
	dthora_atualizacao timestamp NULL,
	cnpj_cliente varchar(120) NULL
);

CREATE TABLE live.dcliente_fornec_loja (
	pk_cliente_fornec varchar(21) NULL,
	nome_cliente varchar(60) NULL,
	razao_cliente varchar(60) NULL,
	tipo_cliente varchar(1) NULL,
	endereco varchar(250) NULL,
	pais varchar(80) NULL,
	fone_cliente varchar(20) NULL,
	email_cliente varchar(50) NULL,
	sexo varchar(1) NULL,
	dt_cadastro timestamp NULL,
	ativo varchar(1) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE live.dcolecoes (
	cod_colecao numeric(3) NULL,
	desc_colecao text NULL,
	sigla_colecao text NULL
);

CREATE TABLE live.dcolecoes_subcolecoes (
	referencia text NULL,
	colecao numeric(3) NULL,
	desc_colecao text NULL,
	cod_subcolecao numeric(38, 10) NULL,
	desc_sub_colecao text NULL
);

CREATE TABLE live.dconjuntos (
	cod_empresa int2 NULL,
	cor_ref_a varchar(6) NULL,
	cor_ref_b varchar(6) NULL,
	referencia_a varchar(5) NULL,
	referencia_b varchar(5) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE live.dfornecedor (
	pk_fornecedor varchar(25) NULL,
	nm_fornecedor varchar(60) NULL,
	cd_situacao_fornecedor int2 NULL,
	telefone_fornecedor int4 NULL,
	cep_fornecedor int4 NULL,
	endereco_fornecedor varchar(80) NULL,
	nr_endereco varchar(25) NULL,
	bairro_fornecedor varchar(40) NULL,
	cidade_fornecedor varchar(60) NULL,
	uf_fornecedor varchar(2) NULL,
	dt_cadastro_fornecedor timestamp NULL,
	dthora_atualizacao timestamp NULL,
	nm_fantasia varchar(80) NULL
);

CREATE TABLE live.dimg_produtos (
	id_produto varchar(20) NULL,
	referencia varchar(20) NULL,
	cor varchar(20) NULL,
	seq_imagem int8 NULL,
	imagem_url varchar(3000) NULL,
	imagem_base64 text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE live.dlojas (
	pk_loja int4 NULL,
	desc_loja varchar(200) NULL,
	desc_apelido varchar(200) NULL,
	desc_razao_social varchar(200) NULL,
	pk_cnpj varchar(35) NULL,
	cod_inscricao_estadual varchar(20) NULL,
	cod_funcionario int4 NULL,
	cep int4 NULL,
	desc_endereco varchar(200) NULL,
	telefone int8 NULL,
	cod_portal varchar(20) NULL,
	pk_portal int4 NULL,
	dt_inauguracao timestamp NULL,
	metragem numeric(7, 2) NULL,
	cod_regiao int4 NULL,
	cod_usuario int4 NULL,
	flag_abre_aos_domingos int2 NULL,
	omny_channel int2 NULL,
	cod_rede int4 NULL,
	porc_franchising numeric(7, 2) NULL,
	ponto_retirada int2 NULL,
	cupom_desconto_loja varchar(20) NULL,
	dt_cadastro timestamp NULL,
	dt_ult_alteracao timestamp NULL,
	cod_cidade int4 NULL,
	cidade varchar(40) NULL,
	estado varchar(2) NULL,
	regiao varchar(100) NULL,
	rede varchar(50) NULL,
	situacao varchar(7) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE live.dperiodo_colecoes (
	id int4 NULL,
	colecao int2 NULL,
	descr_colecao varchar(20) NULL,
	subcolecao int2 NULL,
	descr_sub_colecao varchar(20) NULL,
	classificacao int2 NULL,
	descr_classificacao varchar(6) NULL,
	data_inicio_sell_in timestamp NULL,
	data_fim_sell_in timestamp NULL,
	data_inicio_sell_out timestamp NULL,
	data_fim_sell_out timestamp NULL,
	data_inicio_producao timestamp NULL,
	data_fim_producao timestamp NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE live.dproduto (
	pk_produto varchar(25) NULL,
	pk_produto_cigam varchar(14) NULL,
	cd_produto varchar(16) NULL,
	cd_desc_prod varchar(80) NULL,
	nivel_estrutura int2 NULL,
	desc_nivel_estrutura varchar(30) NULL,
	cd_referencia varchar(5) NULL,
	desc_produto varchar(70) NULL,
	und_medida varchar(2) NULL,
	desc_unidade_medida varchar(20) NULL,
	nm_tamanho varchar(15) NULL,
	nm_cor varchar(25) NULL,
	cd_colecao int2 NULL,
	desc_colecao varchar(30) NULL,
	cod_linha int4 NULL,
	linha_produto varchar(40) NULL,
	cod_artigo int2 NULL,
	desc_artigo varchar(30) NULL,
	artigos_cotas int2 NULL,
	desc_artigo_cotas varchar(30) NULL,
	cd_desc_referencia varchar(50) NULL,
	cod_desc_artigo varchar(50) NULL,
	cod_agrupador int2 NULL,
	desc_agrupador varchar(50) NULL,
	tipo_produto varchar(15) NULL,
	marca varchar(50) NULL,
	cd_conta_estoque int2 NULL,
	desc_conta_estoque varchar(50) NULL,
	desc_produto_narrativa varchar(90) NULL,
	cd_cor varchar(6) NULL,
	cd_tamanho varchar(5) NULL,
	desc_narrativa varchar(70) NULL,
	preco_custo numeric(18, 3) NULL,
	item_ativo int2 NULL,
	desc_referencia varchar(40) NULL,
	desc_segmento varchar(60) NULL,
	publico_alvo varchar(60) NULL,
	faixa_etaria varchar(60) NULL,
	codigo_contabil int4 NULL,
	classific_fiscal varchar(15) NULL,
	descr_class_fisc varchar(40) NULL,
	serie_tamanho int2 NULL,
	desc_serie_tamanho varchar(10) NULL,
	obs_serie_tamanho varchar(60) NULL,
	sub_colecao varchar(20) NULL,
	familia1 varchar(80) NULL,
	familia2 varchar(80) NULL,
	familia3 varchar(80) NULL,
	familia4 varchar(80) NULL,
	familia5 varchar(80) NULL,
	dthora_atualizacao timestamp NULL,
	sku_produto varchar(120) NULL,
	cod_subcolecao int4 NULL,
	desc_sub_colecao varchar(20) NULL,
	origem_prod numeric(1) NULL
);

CREATE TABLE live.dproduto_loja (
	pk_produto varchar(41) NULL,
	desc_produto varchar(80) NULL,
	cod_ncm varchar(20) NULL,
	cod_cest varchar(10) NULL,
	cod_referencia varchar(20) NULL,
	desc_unidade varchar(10) NULL,
	desc_tamanho varchar(50) NULL,
	desc_setor varchar(30) NULL,
	desc_linha varchar(30) NULL,
	desc_marca varchar(30) NULL,
	desc_cor varchar(30) NULL,
	desc_colecao varchar(50) NULL,
	desc_classificacao varchar(50) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE live.dreferencias_mta (
	referencia varchar(50) NULL,
	tamanho varchar(20) NULL,
	corvenda varchar(50) NULL,
	linkimagem text NULL,
	refcor varchar(50) NULL,
	colecao varchar(100) NULL,
	categoria varchar(100) NULL,
	mpprincipal varchar(100) NULL,
	sellin numeric(18, 2) NULL,
	sellout numeric(18, 2) NULL,
	lancamento date NULL,
	descricaocor varchar(255) NULL,
	linha varchar(50) NULL,
	descricaolinha varchar(255) NULL,
	codigoinformacao int4 NULL,
	descricaocodigo varchar(255) NULL,
	artigo varchar(50) NULL,
	desricaoartigo varchar(255) NULL,
	descricaocomercial varchar(255) NULL,
	dereferencias varchar(255) NULL,
	datainicio date NULL,
	datafim date NULL,
	ultima_atualizacao timestamp NULL,
	status varchar(15) NULL
);

CREATE TABLE live.dregiao_lojas (
	cod_regiao int4 NULL,
	desc_regiao varchar(40) NULL,
	cod_cidade int4 NULL
);

CREATE TABLE live.dresponsavel_loja (
	pk_responsavel varchar(80) NULL,
	cod_loja int4 NULL,
	desc_responsavel varchar(100) NULL,
	cargo varchar(200) NULL,
	cod_situacao int2 NULL,
	dthora_atualizacao timestamp NULL,
	email text NULL,
	cod_funcao int4 NULL
);

CREATE TABLE live.dshowroom (
	id serial4 NOT NULL,
	nome_showroom varchar NULL,
	data_inicio date NULL, -- Início período para considerar pedidos deste showroom
	data_fim date NULL, -- Fim período para considerar pedidos deste showroom
	colecao _int4 NULL,
	subcolecao _int4 NULL,
	CONSTRAINT dshowroom_pk PRIMARY KEY (id)
);