-- Schema: stage
-- Tabelas: 20

CREATE TABLE stage.dstg_evento_stage (
	pk_evento text NULL,
	cd_evento numeric(4) NULL,
	cd_tipo_evento numeric(1) NULL,
	ds_evento text NULL,
	ds_evento_codigo text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE stage.fmovimentosinteg_stage (
	portal int8 NULL,
	numorcamento int8 NULL,
	usuario int8 NULL,
	numnf int8 NULL,
	serie varchar(10) NULL,
	chave_nf varchar(100) NULL,
	hora_lancamento varchar(20) NULL,
	codigo_cliente int8 NULL,
	doc_cliente varchar(20) NULL,
	id_cfop varchar(20) NULL,
	cod_vendedor int8 NULL,
	operacao varchar(10) NULL,
	tipo_transacao varchar(10) NULL,
	cancelado varchar(3) NULL,
	seqitem int4 NULL,
	ultima_atualizacao timestamp NULL,
	desconto numeric(18, 3) NULL,
	preco_custo numeric(18, 3) NULL,
	valor_icms numeric(18, 3) NULL,
	aliquota_icms numeric(18, 3) NULL,
	base_icms numeric(18, 3) NULL,
	valor_ipi numeric(18, 3) NULL,
	aliquota_ipi numeric(18, 3) NULL,
	base_ipi numeric(18, 3) NULL,
	valor_cofins numeric(18, 3) NULL,
	aliquota_cofins numeric(18, 3) NULL,
	base_cofins numeric(18, 3) NULL,
	valor_pis numeric(18, 3) NULL,
	aliquota_pis numeric(18, 3) NULL,
	base_pis numeric(18, 3) NULL,
	fk_cliente varchar(40) NULL,
	cnpj varchar(40) NULL,
	valor_bruto int8 NULL,
	cor varchar(6) NULL,
	tamanho varchar(5) NULL,
	considerarvenda varchar(1) NULL,
	desc_movimento varchar(255) NULL,
	fk_produto varchar(25) NULL,
	descricao varchar(200) NULL,
	rede varchar(100) NULL,
	canal_distribuicao varchar(14) NULL,
	flag_movimentacao varchar(20) NULL,
	valor_liquido numeric(18, 3) NULL,
	qtde numeric(18, 3) NULL,
	cst_icms varchar(15) NULL,
	cst_ipi varchar(15) NULL,
	cst_cofins varchar(15) NULL,
	cst_pis varchar(15) NULL,
	data_lancamento timestamp NULL,
	datcancel timestamp NULL,
	cod_barra varchar(20) NULL,
	data_inicio_vigencia date NULL,
	data_fim_vigencia date NULL,
	cnpj_original varchar(40) NULL,
	cnpj_antigo varchar(18) NULL,
	de varchar(20) NULL,
	para varchar(20) NULL,
	loja_original varchar(30) NULL,
	situacao int2 NULL,
	identificador varchar(60) NULL,
	cnpj_emp varchar(20) NULL,
	loja varchar(5) NULL
);

CREATE TABLE stage.fordens_corte_hist_stage (
	id varchar(25) NULL
);

CREATE TABLE stage.fordens_corte_stage (
	cd_ordem_producao int4 NULL,
	cd_grupo varchar(5) NULL,
	prod_rej_item varchar(6) NULL,
	periodo_producao int2 NULL,
	cd_ordem_confeccao int4 NULL,
	situacao_ordem int2 NULL,
	numero_ordem_externa int4 NULL,
	data_alteracao timestamp NULL,
	tamanho varchar(3) NULL,
	data_producao timestamp NULL,
	dthora_atualizacao timestamp NULL,
	dt_lancamento timestamp NULL,
	dt_prevista timestamp NULL,
	prioridade int4 NULL,
	data_programacao timestamp NULL,
	periodo_producao_capa int2 NULL,
	numero_programa int2 NULL,
	cod_cancelamento int2 NULL,
	cd_nivel99 float8 NULL,
	cd_subgrupo varchar(5) NULL,
	cd_estagio int4 NULL,
	qtd_pecas_progamada numeric(18, 3) NULL,
	qtd_pecas_produzida numeric(18, 3) NULL,
	qtd_conserto numeric(18, 3) NULL,
	qtd_pecas_2a numeric(18, 3) NULL,
	estagio_anterior int4 NULL,
	seq_ordem_serv int2 NULL,
	qtd_perdas numeric(18, 3) NULL,
	sequencia_estagio int2 NULL,
	usuario varchar(250) NULL,
	seq_operacao int2 NULL,
	qtd_em_producao_pacote numeric(18, 3) NULL,
	minutos_unitario numeric(18, 3) NULL,
	minutos_total numeric(18, 3) NULL,
	minutos_total_em_producao numeric(18, 3) NULL,
	sequencia_tamanho int4 NULL,
	qtd_marcacoes numeric(18, 3) NULL,
	qtd_a_produzir numeric(18, 3) NULL,
	rowid varchar(100) NULL,
	fk_produto varchar(125) NULL,
	fk_fornecedor varchar(150) NULL,
	alternativa_peca int4 NULL,
	deposito_entrada int4 NULL
);

CREATE TABLE stage.fstg_corte_40 (
	cd_ordem_producao int8 NULL,
	cd_nivel99 varchar(1) NULL,
	cd_grupo varchar(5) NULL,
	cd_subgrupo varchar(3) NULL,
	prod_rej_item varchar(6) NULL,
	cd_estagio int2 NULL,
	periodo_producao int4 NULL,
	cd_ordem_confeccao int4 NULL,
	qtd_pecas_progamada numeric(18, 3) NULL,
	qtd_conserto numeric(18, 3) NULL,
	qtd_pecas_2a numeric(18, 3) NULL,
	estagio_anterior int2 NULL,
	situacao_ordem int2 NULL,
	numero_ordem_externa int4 NULL,
	seq_ordem_serv int4 NULL,
	qtd_perdas numeric(18, 3) NULL,
	sequencia_estagio int4 NULL,
	usuario varchar(250) NULL,
	seq_operacao int2 NULL,
	data_alteracao timestamp NULL,
	qtd_em_producao_pacote numeric(18, 3) NULL,
	fk_produto varchar(18) NULL,
	dthora_atualizacao timestamp NULL,
	cd_barra varchar(18) NULL
);

CREATE TABLE stage.ftabelaprecogrupoest (
	tabela_preco text NULL,
	tabela_preco_cod text NULL,
	grupo_estrutura text NULL,
	item_estrutura text NULL,
	subgru_estrutura text NULL,
	nivel_estrutura text NULL,
	val_tabela_preco numeric(19, 6) NULL
);

CREATE TABLE stage.ftabelaprecostage (
	tabela_preco varchar(9) NULL,
	tabela_preco_cod varchar(11) NULL,
	fk_produto varchar(18) NULL,
	val_tabela_preco numeric(18, 3) NULL,
	vlr_com_desconto numeric(18, 3) NULL,
	grupo_estrutura varchar(5) NULL,
	dthora_atualizacao timestamp NULL
);

CREATE TABLE stage.lojas_vigencia_stage (
	id int4 NULL,
	data_fim_vigencia timestamp NULL,
	portal_antigo varchar(35) NULL,
	portal_novo varchar(35) NULL,
	ordem_troca varchar(35) NULL,
	id_portal_fixo varchar(35) NULL,
	data_criacao timestamp NULL,
	usuario_criacao varchar(35) NULL,
	ultima_atualizacao timestamp NULL,
	cnpj_antigo_completo varchar(15) NULL,
	cnpj_atual_completo varchar(15) NULL,
	cnpj_antigo varchar(14) NULL,
	cnpj_atual varchar(14) NULL,
	data_inicio_vigencia timestamp NULL
);

CREATE TABLE stage.pedi100 (
	pedido_venda numeric(9) NULL,
	data_entr_venda timestamp NULL,
	situacao_venda numeric(2) NULL,
	cod_cancelamento numeric(3) NULL,
	sit_aloc_pedi numeric(1) NULL,
	sit_coletor numeric(1) NULL,
	situacao_coleta numeric(1) NULL,
	status_expedicao numeric(1) NULL,
	status_homologacao numeric(1) NULL,
	status_pedido numeric(1) NULL,
	status_comercial numeric(1) NULL,
	sit_conferencia numeric(1) NULL,
	qtde_saldo_pedi numeric(15, 3) NULL,
	valor_saldo_pedi numeric(15, 3) NULL,
	ultima_atualizacao timestamp NULL,
	qtde_total_pedi numeric(15, 3) NULL,
	live_data_entr_venda_original timestamp NULL
);

CREATE TABLE stage.pedi135 (
	pedido_venda numeric(9) NULL,
	seq_situacao numeric(2) NULL,
	codigo_situacao numeric(2) NULL,
	flag_liberacao varchar(5) NULL,
	data_situacao timestamp NULL,
	data_liberacao timestamp NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE stage.stage_movimentacoes_integ (
	portal_movimentacao int8 NULL,
	identificador varchar(60) NULL,
	cnpj_movimentacao varchar(40) NULL,
	numorcamento int8 NULL,
	usuario int8 NULL,
	numnf int8 NULL,
	serie varchar(10) NULL,
	chave_nf varchar(100) NULL,
	qtde numeric(18, 3) NULL,
	valor_liquido numeric(18, 3) NULL,
	desconto numeric(18, 3) NULL,
	preco_custo numeric(18, 3) NULL,
	fk_produto varchar(168) NULL,
	data_lancamento timestamp NULL,
	hora_lancamento varchar(20) NULL,
	codigo_cliente int8 NULL,
	doc_cliente varchar(20) NULL,
	id_cfop varchar(20) NULL,
	cod_vendedor int8 NULL,
	cst_icms varchar(10) NULL,
	valor_icms numeric(18, 3) NULL,
	aliquota_icms numeric(18, 3) NULL,
	base_icms numeric(18, 3) NULL,
	cst_ipi varchar(10) NULL,
	valor_ipi numeric(20, 5) NULL,
	aliquota_ipi numeric(18, 3) NULL,
	base_ipi numeric(18, 3) NULL,
	cst_cofins varchar(10) NULL,
	valor_cofins numeric(18, 3) NULL,
	aliquota_cofins numeric(18, 3) NULL,
	base_cofins numeric(18, 3) NULL,
	cst_pis varchar(10) NULL,
	valor_pis numeric(18, 3) NULL,
	aliquota_pis numeric(18, 3) NULL,
	base_pis numeric(18, 3) NULL,
	operacao varchar(10) NULL,
	tipo_transacao varchar(10) NULL,
	cancelado varchar(1) NULL,
	datcancel timestamp NULL,
	seqitem int4 NULL,
	ultima_atualizacao timestamp NULL,
	valor_bruto numeric(18, 3) NULL,
	cor varchar(20) NULL,
	tamanho varchar(32) NULL,
	considerarvenda varchar(1) NULL,
	desc_movimento varchar(255) NULL,
	cod_barra varchar(20) NULL,
	loja_movimentacao varchar(30) NULL
);

CREATE TABLE stage.stg_cnpj_ativos_integ (
	cnpj_antigo varchar(20) NULL,
	cnpj_atual varchar(20) NULL,
	data_inicio_vigencia date NULL,
	data_fim_vigencia date NULL,
	portal_antigo varchar(20) NULL,
	portal_atual varchar(20) NULL
);

CREATE TABLE stage.stg_evidencias (
	answer_id varchar(100) NULL,
	answer_evidence_type_id varchar(100) NULL,
	answer_url text NULL,
	answer_evidence_type_id_ref varchar(100) NULL,
	answer_evidence_type_name_ref varchar(100) NULL
);

CREATE TABLE stage.stg_infos_lojas_integ (
	id_loja int4 NULL,
	descricao varchar(200) NULL,
	apelido varchar(200) NULL,
	razao_social varchar(200) NULL,
	situacao int2 NULL,
	endereco varchar(200) NULL,
	cep int4 NULL,
	id_portal int4 NULL,
	data_inauguracao timestamp NULL,
	cnpj varchar(100) NULL,
	portal varchar(72) NULL,
	rede varchar(100) NULL
);

CREATE TABLE stage.stg_movimentos_integ (
	portal int8 NULL,
	identificador varchar(60) NULL,
	cnpj_emp varchar(40) NULL,
	numorcamento int8 NULL,
	usuario int8 NULL,
	numnf int8 NULL,
	serie varchar(10) NULL,
	chave_nf varchar(100) NULL,
	fk_produto varchar(168) NULL,
	data_lancamento timestamp NULL,
	hora_lancamento varchar(20) NULL,
	codigo_cliente int8 NULL,
	doc_cliente varchar(20) NULL,
	id_cfop varchar(20) NULL,
	cod_vendedor int8 NULL,
	cst_icms varchar(10) NULL,
	aliquota_icms numeric(20, 5) NULL,
	base_icms numeric(20, 5) NULL,
	cst_ipi varchar(10) NULL,
	valor_ipi numeric(20, 5) NULL,
	aliquota_ipi numeric(20, 5) NULL,
	base_ipi numeric(20, 5) NULL,
	cst_cofins varchar(10) NULL,
	valor_cofins numeric(20, 5) NULL,
	aliquota_cofins numeric(20, 5) NULL,
	base_cofins numeric(20, 5) NULL,
	cst_pis varchar(10) NULL,
	valor_pis numeric(20, 5) NULL,
	aliquota_pis numeric(20, 5) NULL,
	base_pis numeric(20, 5) NULL,
	operacao varchar(10) NULL,
	tipo_transacao varchar(10) NULL,
	cancelado varchar(1) NULL,
	datcancel timestamp NULL,
	seqitem int4 NULL,
	ultima_atualizacao timestamp NULL,
	valor_bruto float8 NULL,
	cor varchar(20) NULL,
	tamanho varchar(32) NULL,
	considerarvenda varchar(1) NULL,
	desc_movimento varchar(255) NULL,
	cod_barra varchar(20) NULL,
	loja_movimentacao varchar(10) NULL,
	qtde numeric(20, 5) NULL,
	valor_liquido numeric(20, 5) NULL,
	desconto numeric(20, 5) NULL,
	preco_custo numeric(20, 5) NULL,
	valor_icms numeric(20, 5) NULL
);

CREATE TABLE stage.stg_movimentos_integ_full (
	portal numeric(10) NULL,
	identificador text NULL,
	cnpj_emp text NULL,
	numorcamento numeric(10) NULL,
	usuario numeric(10) NULL,
	numnf numeric(10) NULL,
	serie text NULL,
	chave_nf text NULL,
	qtde numeric(15, 5) NULL,
	valor_liquido numeric(15, 5) NULL,
	desconto numeric(15, 5) NULL,
	preco_custo numeric(15, 5) NULL,
	fk_produto text NULL,
	data_lancamento timestamp NULL,
	hora_lancamento text NULL,
	codigo_cliente numeric(10) NULL,
	doc_cliente text NULL,
	id_cfop text NULL,
	cod_vendedor numeric(10) NULL,
	cst_icms text NULL,
	valor_icms numeric(15, 5) NULL,
	aliquota_icms numeric(15, 5) NULL,
	base_icms numeric(15, 5) NULL,
	cst_ipi text NULL,
	valor_ipi numeric(15, 5) NULL,
	aliquota_ipi numeric(15, 5) NULL,
	base_ipi numeric(15, 5) NULL,
	cst_cofins text NULL,
	valor_cofins numeric(15, 5) NULL,
	aliquota_cofins numeric(15, 5) NULL,
	base_cofins numeric(15, 5) NULL,
	cst_pis text NULL,
	valor_pis numeric(15, 5) NULL,
	aliquota_pis numeric(15, 5) NULL,
	base_pis numeric(15, 5) NULL,
	operacao text NULL,
	tipo_transacao text NULL,
	cancelado text NULL,
	datcancel timestamp NULL,
	seqitem numeric(6) NULL,
	ultima_atualizacao timestamp NULL,
	valor_bruto numeric(38, 10) NULL,
	cor text NULL,
	tamanho text NULL,
	considerarvenda text NULL,
	desc_movimento text NULL,
	cod_barra text NULL,
	loja_movimentacao text NULL
);

CREATE TABLE stage.stg_paradasmaquinas_marft_oper (
	cod_operador numeric(5) NULL,
	nome_operador text NULL,
	"data" timestamp NULL,
	hora_inicio timestamp NULL,
	hora_fim timestamp NULL,
	minutos numeric(5) NULL,
	codigo_motivo numeric(3) NULL,
	motivo text NULL,
	detalhes text NULL,
	codigo_celula numeric(5) NULL,
	nome_celula text NULL,
	turno numeric(3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE stage.stg_paradasmaquinas_marft_pmo (
	cod_operador numeric(5) NULL,
	nome_operador text NULL,
	"data" timestamp NULL,
	hora_inicio timestamp NULL,
	hora_fim timestamp NULL,
	minutos numeric(5) NULL,
	codigo_motivo numeric(3) NULL,
	motivo text NULL,
	detalhes text NULL,
	codigo_celula numeric(5) NULL,
	nome_celula text NULL,
	turno numeric(3) NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE stage.stg_planos (
	id varchar(100) NULL,
	task_code varchar(100) NULL,
	creator_user_id varchar(100) NULL,
	created_at varchar(100) NULL,
	updated_at varchar(100) NULL,
	checklist_execution_id varchar(100) NULL,
	question_id varchar(100) NULL,
	action_plan_state_id varchar(100) NULL,
	action_plan_state_name varchar(100) NULL,
	user_id varchar(100) NULL,
	user_name varchar(100) NULL,
	user_role varchar(100) NULL,
	answer_id varchar(100) NULL,
	answer_respondent_user_id varchar(100) NULL,
	answer_approver_user_id varchar(100) NULL,
	answer_answer varchar(1000) NULL
);

CREATE TABLE stage.stg_sugestao_reserva_tecido_oc (
	cd_ordem_producao varchar(25) NULL,
	periodo_producao varchar(25) NULL,
	cd_estagio varchar(25) NULL,
	referencia varchar(5) NULL,
	cod_cor varchar(6) NULL,
	fk_produto varchar(40) NULL,
	fk_componente varchar(40) NULL,
	unidade_medida varchar(2) NULL,
	qtd_a_produzir numeric(17, 2) NULL,
	qtd_em_producao_pacote numeric(17, 2) NULL,
	qtd_pecas_progamada numeric(17, 2) NULL,
	consumo_programado numeric(17, 2) NULL
);