-- Schema: suprimentos
-- Tabelas: 15

CREATE TABLE suprimentos.dfornecedor_produto (
	"código produto" text NULL,
	descrição text NULL,
	"cnpj fornecedor" text NULL,
	nome_fornecedor text NULL,
	codigo_fornecedor text NULL,
	tempo_reposicao numeric(5) NULL,
	lote_multiplo numeric(12, 3) NULL,
	codigo_moeda numeric(2) NULL,
	unid_conv text NULL,
	fator_conv numeric(14, 6) NULL,
	qtde_por_embalagem numeric(13, 3) NULL,
	operador_calc text NULL,
	desc_referencia varchar(85) NULL
);

CREATE TABLE suprimentos.dlancamentos_produto (
	produto text NULL,
	num_contabil numeric(9) NULL,
	documento numeric(9) NULL,
	centro_de_custo text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE suprimentos.dlancamentos_servico (
	produto text NULL,
	num_contabil numeric(9) NULL,
	nr_duplicata numeric(9) NULL,
	centro_de_custo text NULL,
	ultima_atualizacao timestamp NULL
);

CREATE TABLE suprimentos.dobc_empresas (
	id_filial text NULL,
	filial_razao_social text NULL,
	filial_nome_fantasia text NULL,
	filial_status text NULL,
	filial_empresa text NULL,
	id_empresa text NULL,
	filial_status_nome text NULL
);

CREATE TABLE suprimentos.dobc_sdcv_detalhes (
	sdcv_codigo numeric(15) NULL,
	sdcv_requisicao_erp text NULL,
	sdcv_prioridade text NULL,
	sdcv_motivo_urgencia text NULL,
	sdc_descricao_adicional text NULL,
	sdc_motivo_outro text NULL,
	sdc_descricao text NULL,
	comentario_uso_interno text NULL,
	sdcv_tipo text NULL,
	sdcv_tipo_registro text NULL,
	sdcv_tipo_compra text NULL,
	contrato_numero int4 NULL,
	sdcv_solicitante text NULL,
	sdcv_comprador text NULL,
	sdcv_c_custo_codigo text NULL,
	sdcv_c_custo_nome text NULL,
	sdcv_c_contabil_codigo text NULL,
	sdcv_c_contabil_nome text NULL,
	sdcv_empresa text NULL,
	sdcv_filial_nome text NULL,
	sdcv_filial_razao_social text NULL,
	sdcv_local_entrega_nome text NULL,
	sdcv_grupo_descricao text NULL,
	sdcv_quantidade numeric(38, 18) NULL,
	sdcv_unidade text NULL,
	sdcv_de_projeto text NULL,
	projeto_codigo int8 NULL,
	projeto_nome text NULL,
	projeto_fase_codigo int4 NULL,
	projeto_fase text NULL,
	categoria_nivel_1 text NULL,
	categoria_nivel_2 text NULL,
	categoria_nivel_3 text NULL,
	caracteristica_item text NULL,
	item_codigo int4 NULL,
	item_codigo_erp text NULL,
	item_nome text NULL,
	proposta_de_contrato text NULL,
	proposta_frete text NULL,
	proposta_valor_frete numeric(38, 18) NULL,
	proposta_vlr_unit numeric(38, 18) NULL,
	proposta_vlr_total numeric(38, 18) NULL,
	proposta_vlr_unit_inicial numeric(38, 18) NULL,
	proposta_vlr_total_inicial numeric(38, 18) NULL,
	proposta_custo_unit numeric(38, 18) NULL,
	proposta_custo_total numeric(38, 18) NULL,
	saving_vlr_valor_saving numeric(38, 18) NULL,
	saving_vlr_valor_base_saving numeric(38, 18) NULL,
	saving_vlr_percentual_saving numeric(38, 18) NULL,
	saving_cus_valor_saving numeric(38, 18) NULL,
	saving_cus_valor_base_saving numeric(38, 18) NULL,
	saving_cus_percentual_saving numeric(38, 18) NULL,
	proposta_saving_vlr numeric(38, 18) NULL,
	proposta_valor_base_para_saving numeric(38, 18) NULL,
	proposta_saving_percentual numeric(38, 18) NULL,
	proposta_saving_base_calculo text NULL,
	proposta_saving_tipo text NULL,
	proposta_vlr_considerado_analise_cotacao numeric(38, 18) NULL,
	proposta_cond_pagamento text NULL,
	proposta_prazo_medio_pagamento numeric(10, 2) NULL,
	proposta_moeda text NULL,
	proposta_renegociada text NULL,
	proposta_preenchida_por text NULL,
	proposta_justificativa_escolha text NULL,
	fornecedor_razao_social text NULL,
	fornecedor_fantasia text NULL,
	fornecedor_cnpj text NULL,
	fornecedor_cidade text NULL,
	fornecedor_estado text NULL,
	fornecedor_faturado text NULL,
	cnpj_faturado text NULL,
	compra_numero int4 NULL,
	pedido_numero text NULL,
	pedido_qtd_pedida numeric(38, 18) NULL,
	pedido_qtd_recebida numeric(38, 18) NULL,
	pedido_qtd_saldo numeric(38, 18) NULL,
	pedido_situacao_entrega text NULL,
	pedido_status_entrega text NULL,
	nf_numero text NULL,
	nf_serie text NULL,
	nf_data_emissao text NULL,
	nf_quantidade_entrega text NULL,
	data_compra_dia text NULL,
	data_compra_mes text NULL,
	data_compra_ano text NULL,
	data_criacao_sdcv text NULL,
	data_expectativa_sugerida text NULL,
	data_expectativa_informada text NULL,
	data_ultima_autorizacao text NULL,
	data_envio_aprovacao_cotacao text NULL,
	data_ultima_aprovacao_cotacao text NULL,
	data_integracao_erp text NULL,
	data_emissao_pedido text NULL,
	data_previsao_faturamento text NULL,
	data_previsao_entrega text NULL,
	data_primeira_entrega text NULL,
	data_ultima_entrega text NULL,
	prazo_sugerido int4 NULL,
	prazo_solicitante int4 NULL,
	tempo_entre_solicitacao_compra int4 NULL,
	tempo_entre_solicitacao_entrega int4 NULL,
	tempo_atendeu_prazo_solicitante text NULL,
	tempo_fornecedor_atendeu_prazo_pedido text NULL,
	quantidade_convites int4 NULL,
	quantidade_respostas int4 NULL,
	quantidade_declinadas int4 NULL,
	quantidade_nao_responderam int4 NULL,
	saving_uc_percentual numeric(38, 18) NULL,
	saving_uc_valor numeric(38, 18) NULL,
	saving_ge_percentual numeric(38, 18) NULL,
	saving_ge_valor numeric(38, 18) NULL,
	saving_gf_percentual numeric(38, 18) NULL,
	saving_gf_valor numeric(38, 18) NULL,
	saving_ce_percentual numeric(38, 18) NULL,
	saving_ce_valor numeric(38, 18) NULL,
	saving_ma_percentual numeric(38, 18) NULL,
	saving_ma_valor numeric(38, 18) NULL,
	compra_tipo_compra text NULL,
	sdc_for_exclusivo text NULL,
	tempo_criacao numeric(10, 2) NULL,
	tempo_triagem numeric(10, 2) NULL,
	tempo_convite numeric(10, 2) NULL,
	tempo_cotacao numeric(10, 2) NULL,
	tempo_aprovacao numeric(10, 2) NULL,
	tempo_aprovacao_pedido numeric(10, 2) NULL,
	tempo_pedido numeric(10, 2) NULL,
	tempo_faturamento numeric(10, 2) NULL,
	tempo_entrega numeric(10, 2) NULL,
	tempo_comprador numeric(10, 2) NULL,
	tempo_aprovador numeric(10, 2) NULL,
	tempo_solicitante numeric(10, 2) NULL,
	tempo_fornecedor numeric(10, 2) NULL,
	tempo_total numeric(10, 2) NULL,
	motivo_codigo_erp text NULL,
	motivo_descricao text NULL,
	centro_de_custo_cod text NULL,
	sdc_status text NULL,
	requisicao_grupo text NULL,
	cotacao_codigo int4 NULL,
	sequencial_pedido int4 NULL,
	compra_cond_pagamento text NULL,
	compra_prazo_medio_pagamento numeric(10, 2) NULL,
	sdcv_target numeric(18, 6) NULL,
	nota_primeiro_vencimento timestamp NULL,
	nota_item_valor numeric(38, 18) NULL,
	projeto_valor_aprovado numeric(38, 18) NULL
);

CREATE TABLE suprimentos.dobc_sdcv_resumo (
	id_sdcv numeric(15) NULL,
	sdcv_status text NULL,
	sdcv_status_nome text NULL,
	sdcv_tipo text NULL,
	sdcv_prioridade text NULL,
	sdcv_tipo_registro text NULL,
	sdcv_tipo_compra text NULL,
	sdcv_qtdade numeric(38, 18) NULL,
	sdcv_valor_total numeric(38, 18) NULL,
	sdcv_vlr_frete_fornecedor numeric(38, 18) NULL,
	sdcv_saving_valor numeric(38, 18) NULL,
	sdcv_saving_percentual numeric(38, 18) NULL,
	sdcv_saving_tipo text NULL,
	sdcv_moeda text NULL,
	sdcv_data_criacao text NULL,
	sdcv_data_envio_cotacao text NULL,
	sdcv_data_envio_aprovacao text NULL,
	sdcv_data_compra text NULL,
	id_solicitante text NULL,
	id_comprador text NULL,
	id_item text NULL,
	sdcv_filial_razao text NULL,
	id_filial text NULL,
	sdcv_empresa_nome text NULL,
	id_projeto int8 NULL,
	id_fase_projeto int4 NULL,
	id_contrato int4 NULL,
	id_pedido text NULL,
	id_compra int4 NULL,
	id_cotacao int4 NULL,
	sdcv_motivo text NULL,
	sdcv_descricao_complementar text NULL,
	sdcv_descricao_interna text NULL,
	sdcv_motivo_escolha_fornecedor text NULL,
	sdcv_preenchedor_proposta text NULL,
	sdcv_renegociada text NULL,
	sdc_data_ult_movimentacao timestamp NULL,
	sdc_target numeric(18, 6) NULL
);

CREATE TABLE suprimentos.fauditorio_de_pedido_de_compra (
	titulo numeric(9) NULL,
	tipo_titulo numeric(2) NULL,
	cnpj_titulo text NULL,
	emitente_titulo text NULL,
	centro_custo numeric(6) NULL,
	valor_titulo numeric(38, 10) NULL,
	pedido numeric(38, 10) NULL,
	valor_pedido numeric(38, 10) NULL,
	valor_diferenca numeric(38, 10) NULL,
	encontrado text NULL
);

CREATE TABLE suprimentos.fdados_bi (
	sdcv_tipo text NULL,
	data_criacao_sdcv text NULL,
	data_ultima_entrega text NULL,
	centro_de_custo_cod text NULL,
	projeto_codigo int8 NULL,
	projeto_nome text NULL,
	projeto_fase_codigo int4 NULL,
	projeto_fase text NULL,
	sdcv_empresa text NULL,
	sdcv_c_contabil_codigo text NULL,
	sdcv_codigo numeric(15) NULL,
	pedido_numero text NULL,
	sdcv_solicitante text NULL,
	fornecedor_cnpj text NULL,
	fornecedor_razao_social text NULL,
	item_codigo_erp text NULL,
	item_nome text NULL,
	nf_numero text NULL,
	nota_item_valor numeric(38, 18) NULL,
	nf_data_emissao text NULL,
	nota_primeiro_vencimento timestamp NULL,
	sdc_descricao text NULL,
	sdcv_entrega_emissao text NULL,
	sdcv_entrega_numero_nf text NULL,
	sdcv_valor_total numeric(15, 3) NULL,
	proposta_vlr_unit numeric(15, 3) NULL
);

CREATE TABLE suprimentos.finvestimento_realizado (
	empresa varchar(150) NULL,
	produto varchar(50) NULL,
	numero_nota int4 NULL,
	centro_de_custo varchar(150) NULL,
	fornecedor varchar(20) NULL,
	nome_fornecedor varchar(150) NULL,
	descricao_bem text NULL,
	cod_do_bem varchar(50) NULL,
	observacoes_do_bem text NULL,
	grupo_do_bem varchar(150) NULL,
	grupo_do_produto varchar(150) NULL,
	data_aquisicao date NULL,
	valor_bem numeric(15, 2) NULL,
	ultima_atualizacao timestamp NULL,
	descricao varchar(300) NULL
);

CREATE TABLE suprimentos.fitem_projeto_obc (
	sdcv_codigo int8 NULL,
	prj_codigo int8 NULL,
	prj_nome text NULL,
	data_criacao_sdcv timestamp NULL,
	proposta_prazo_medio_pagamento int4 NULL,
	centro_de_custo_cod text NULL,
	sdcv_c_custo_nome text NULL,
	proposta_cond_pagamento text NULL,
	justificativa text NULL,
	pfa_codigo int8 NULL,
	pfa_descricao text NULL,
	pedido_numero text NULL,
	item_descricao text NULL,
	id_item int8 NULL,
	sdcv_tipo_registro text NULL,
	id_categoria_nivel1 int8 NULL,
	id_categoria_nivel2 int8 NULL,
	item_categoria_nivel1 text NULL,
	item_categoria_nivel2 text NULL,
	item_categoria_nivel3 text NULL,
	item_caracteristica text NULL,
	proposta_vlr_total numeric(18, 2) NULL,
	fornecedor_fantasia text NULL,
	fornecedor_cnpj text NULL,
	proposta_vlr_unit numeric(18, 2) NULL,
	sdcv_unidade text NULL,
	sdcv_quantidade numeric(18, 4) NULL,
	compra_numero int8 NULL,
	sdcv_tipo_compra text NULL,
	sdcv_solicitante text NULL,
	sdcv_comprador text NULL,
	prj_status text NULL,
	sdc_status text NULL,
	prv_valor_previsto numeric(18, 2) NULL,
	prj_valor_aprovado numeric(18, 2) NULL,
	prj_valor_base numeric(18, 2) NULL,
	prv_valor numeric(18, 2) NULL,
	descricao_status varchar(100) NULL,
	tipo varchar(30) NULL,
	etapa varchar(20) NULL,
	subetapa varchar(30) NULL,
	valor_previsto numeric(18, 3) NULL,
	valor_aprovado numeric(18, 3) NULL,
	valor_base numeric(18, 3) NULL,
	valor_unitario numeric(18, 3) NULL,
	valor_total numeric(18, 3) NULL,
	prazo_medio_pgto int4 NULL
);

CREATE TABLE suprimentos.fnota_entrada (
	nf_notafiscal int4 NULL,
	nf_serienotafiscal varchar(5) NULL,
	nf_dataemissao timestamp NULL,
	fk_produto varchar(18) NULL,
	pedido_compra int8 NULL,
	seq_item_pedido_compra int8 NULL,
	fk_cliente varchar(20) NULL,
	fk_fornecedor varchar(20) NULL,
	itemnf_vlr_tot numeric(18, 3) NULL,
	itemnf_quantidade numeric(18, 3) NULL,
	itemnf_vlrunit numeric(18, 3) NULL,
	itemnf_vlrdesconto numeric(18, 3) NULL,
	itemnf_vlripi numeric(18, 3) NULL,
	itemnf_vlricms numeric(18, 3) NULL,
	itemnf_vlricmsdiferido numeric(18, 3) NULL,
	itemnf_vlrpis numeric(18, 3) NULL,
	itemnf_vlrcofins numeric(18, 3) NULL,
	condicao_pagto int2 NULL,
	nf_origem int4 NULL,
	cfop varchar(44) NULL,
	desc_nat_oper varchar(40) NULL,
	uf varchar(2) NULL,
	cd_emite_duplicata varchar(2) NULL,
	emite_duplicata varchar(3) NULL,
	fk_centro_custo int8 NULL,
	fk_conta_estoque int4 NULL,
	codigo_contabil int4 NULL,
	fk_grupo_contas int4 NULL,
	cod_familia int4 NULL,
	descricao_familia varchar(20) NULL,
	ultima_atualizacao timestamp NULL,
	data_digitacao timestamp NULL,
	data_transacao timestamp NULL,
	usuario_digitacao varchar(250) NULL,
	situacao_entrada int2 NULL,
	especie_docto varchar(5) NULL
);

CREATE TABLE suprimentos.fnota_entrada2 (
	nf_notafiscal numeric(9) NULL,
	nf_serienotafiscal text NULL,
	nf_dataemissao timestamp NULL,
	fk_produto text NULL,
	pedido_compra numeric(9) NULL,
	seq_item_pedido_compra numeric(9) NULL,
	fk_cliente text NULL,
	fk_fornecedor text NULL,
	itemnf_vlr_tot numeric(38, 10) NULL,
	itemnf_quantidade numeric(14, 3) NULL,
	itemnf_vlrunit numeric(20, 5) NULL,
	itemnf_vlrdesconto numeric(15, 2) NULL,
	itemnf_vlripi numeric(15, 2) NULL,
	itemnf_vlricms numeric(15, 2) NULL,
	itemnf_vlricmsdiferido numeric(15, 2) NULL,
	itemnf_vlrpis numeric(15, 2) NULL,
	itemnf_vlrcofins numeric(15, 2) NULL,
	condicao_pagto numeric(3) NULL,
	nf_origem numeric(9) NULL,
	cfop text NULL,
	desc_nat_oper text NULL,
	uf text NULL,
	cd_emite_duplicata text NULL,
	emite_duplicata text NULL,
	fk_centro_custo numeric(9) NULL,
	fk_conta_estoque numeric(2) NULL,
	codigo_contabil numeric(6) NULL,
	fk_grupo_contas numeric(3) NULL,
	cod_familia numeric(5) NULL,
	descricao_familia text NULL,
	dthora_atualizacao timestamp NULL,
	data_digitacao timestamp NULL,
	data_transacao timestamp NULL,
	usuario_digitacao text NULL,
	situacao_entrada numeric(1) NULL,
	especie_docto text NULL
);

CREATE TABLE suprimentos.fpendencias_acessorios (
	empresa numeric(3) NULL,
	data_emissao timestamp NULL,
	nota_fiscal numeric(9) NULL,
	serie_nota_fiscal text NULL,
	ordem_servico numeric(9) NULL,
	ordem_producao numeric(9) NULL,
	cnpj_fornecedor text NULL,
	nome_fornecedor text NULL
);

CREATE TABLE suprimentos.fprojeto_obc (
	projeto_codigo int8 NULL,
	projeto_nome text NULL,
	projeto_fase text NULL,
	projeto_fase_codigo int4 NULL,
	prj_data_ini date NULL,
	prj_data_fim date NULL,
	"valor total previsto" numeric(38, 18) NULL,
	"valor total orçado" numeric(38, 18) NULL,
	"valor total empenhado" numeric(38, 18) NULL,
	"valor total empenhado em contrato" numeric(38, 18) NULL,
	"valor total pedidos" numeric(38, 18) NULL,
	"valor total requisicoes de estoque" numeric(38, 18) NULL,
	"valor total notas fiscais" numeric(38, 18) NULL,
	"saldo total" numeric(38, 18) NULL
);

CREATE TABLE suprimentos.frequisicoes_compra (
	num_requisicao numeric(6) NULL,
	seq_item_req numeric(2) NULL,
	codigo_deposito numeric(3) NULL,
	data_requisicao timestamp NULL,
	nome_requisit text NULL,
	observacao_req text NULL,
	data_prev_entr_req timestamp NULL,
	situacao_codigo numeric(1) NULL,
	cod_cancelamento numeric(2) NULL,
	descr_canc_comp text NULL,
	situacao text NULL,
	pedido_compra numeric(6) NULL,
	data_prev_entr_ped timestamp NULL,
	fk_produto text NULL,
	fk_fornecedor text NULL,
	unidade_medida text NULL,
	qtde_requisitada numeric(15, 3) NULL,
	qtde_pedida_item numeric(15, 3) NULL,
	valor_unitario numeric(20, 5) NULL,
	ultimaentrada timestamp NULL,
	ultimasaida timestamp NULL,
	estoqueatual numeric(38, 10) NULL,
	qtdsugerida numeric(38, 10) NULL,
	precoultentrada numeric(38, 10) NULL,
	estoquemin numeric(38, 10) NULL,
	estoquemax numeric(38, 10) NULL,
	consumomedmes numeric(38, 10) NULL,
	consumopordia numeric(38, 10) NULL
);