-- Schema: ti
-- Tabelas: 28

CREATE TABLE ti.ddescricao_prioridade (
	prioridade_id int4 NOT NULL,
	desc_prioridade text NOT NULL,
	CONSTRAINT ddescricao_prioridade_pkey PRIMARY KEY (prioridade_id)
);

CREATE TABLE ti.ddescricao_status (
	status_id int4 NOT NULL,
	descricao_status text NOT NULL,
	CONSTRAINT ddescricao_status_pkey PRIMARY KEY (status_id)
);

CREATE TABLE ti.dglpi_categorias (
	id int4 NOT NULL,
	itilcategories_id int4 NULL,
	categoria_nome varchar(100) DEFAULT NULL::character varying NULL,
	completename varchar(255) DEFAULT NULL::character varying NULL,
	subcategoria varchar(50) DEFAULT NULL::character varying NULL,
	tipo_sistema varchar(50) DEFAULT NULL::character varying NULL,
	CONSTRAINT dglpi_categorias_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.dglpi_estagios (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	depto varchar(50) NULL,
	tipo varchar(50) NULL,
	fase varchar(100) NULL,
	etapa varchar(100) NULL,
	id_tecnico int4 NULL,
	tecnico varchar(100) NULL,
	responsavel varchar(50) NULL,
	resp_tecnico varchar(50) NULL,
	"time" varchar(50) NULL,
	CONSTRAINT dglpi_estagios_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.dglpi_filas (
	id int4 NULL,
	"name" varchar(255) NULL,
	"comment" text NULL,
	fase varchar(255) NULL,
	etapa varchar(255) NULL
);

CREATE TABLE ti.dglpi_grupos (
	id int8 NULL,
	groups_id int8 NULL,
	completename text NULL,
	area text NULL,
	departamento text NULL,
	setor text NULL
);

CREATE TABLE ti.dglpi_sistemas (
	sistemas_id int4 DEFAULT nextval('ti.sistemas_glpi_sistemas_id_seq'::regclass) NOT NULL,
	sistema varchar(255) NOT NULL,
	categoria varchar(255) NOT NULL,
	CONSTRAINT sistemas_glpi_pkey PRIMARY KEY (sistemas_id)
);

CREATE TABLE ti.dglpi_sla (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo_chamado varchar(20) NULL,
	categoria varchar(20) NULL,
	estagio varchar(50) NULL,
	sla int4 NULL,
	CONSTRAINT sla_glpi_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.dglpi_subcategoria_sistemas (
	sub_categoria_id int4 NOT NULL,
	subcategoria_desc varchar(255) NOT NULL,
	categoria_id int4 NOT NULL,
	CONSTRAINT dim_subcategoria_sistemas_glpi_pkey PRIMARY KEY (sub_categoria_id)
);

CREATE TABLE ti.dglpi_times (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fila_glpi varchar(50) NULL,
	"time" varchar(50) NULL,
	CONSTRAINT dfilas_times_glpi_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.dorion_demandas (
	id_demanda int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo varchar(255) NULL,
	sistema varchar(255) NULL,
	data_criacao date NULL,
	data_vencimento date NULL,
	descricao text NULL,
	tipo varchar(50) NULL,
	coluna int4 NULL,
	ordem int4 NULL,
	chamados _int4 NULL,
	prioridade varchar NULL,
	data_solucao date NULL,
	CONSTRAINT dorion_demandas_pkey PRIMARY KEY (id_demanda)
);

CREATE TABLE ti.dorion_iniciativas (
	id_iniciativa int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo varchar(255) NULL,
	sistema varchar(255) NULL,
	data_criacao date NULL,
	id_autor int4 NULL,
	id_responsavel int4 NULL,
	descricao text NULL,
	tipo varchar(50) NULL,
	coluna int4 NULL,
	ordem int4 NULL,
	chamados _int4 NULL,
	CONSTRAINT dorion_iniciativas_pkey PRIMARY KEY (id_iniciativa)
);

CREATE TABLE ti.dorion_map_processos (
	id_map int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	setor varchar(50) NULL,
	processo int4 NULL,
	processo_map int4 NULL,
	subprocesso int4 NULL,
	subprocesso_map int4 NULL,
	detalhe_subprocesso int4 NULL,
	detalhe_subprocesso_map int4 NULL,
	CONSTRAINT dorion_map_processos_pkey PRIMARY KEY (id_map)
);

CREATE TABLE ti.dorion_projetos (
	id varchar(9) NULL,
	cod_projeto varchar(9) NULL,
	data_criacao timestamp NULL,
	origem_projeto varchar(150) NULL,
	descricao varchar(400) NULL,
	descricao_problema varchar(4000) NULL,
	objetivo_projeto varchar(4000) NULL,
	pendencias varchar(4000) NULL,
	acao_em_andamento varchar(4000) NULL,
	proximas_acoes varchar(4000) NULL,
	status varchar(50) NULL
);

CREATE TABLE ti.dsquads (
	squad_id int4 NOT NULL,
	squad_name varchar NULL,
	responsavel varchar NULL,
	backlog int4 NULL,
	icone varchar(50) NULL,
	CONSTRAINT squad_pk PRIMARY KEY (squad_id)
);

CREATE TABLE ti.dsquads_composicao (
	id int4 NOT NULL,
	nome varchar NULL,
	squad_id int4 NULL,
	analista_id int4 NULL
);

CREATE TABLE ti.fat_comentarios_glpi (
	chamado_id int4 NOT NULL,
	titulo_chamado varchar(500) NULL,
	data_ultimo_post timestamp NULL,
	post_texto text NULL,
	user_post varchar(200) NULL,
	CONSTRAINT fat_comentarios_glpi_pkey PRIMARY KEY (chamado_id)
);

CREATE TABLE ti.fglpi_chamados (
	id int4 NOT NULL,
	"date" timestamp NULL,
	closedate timestamp NULL,
	solvedate timestamp NULL,
	tempo_para_solucao timestamp NULL,
	status int4 NULL,
	slas_id_tto int4 NULL,
	slas_id_ttr int4 NULL,
	sla_waiting_duration int4 NULL,
	slalevels_id_ttr int4 NULL,
	priority int4 NULL,
	id_solicitante int4 NULL,
	urgencia int4 NULL,
	tipo_prioridade varchar(50) NULL,
	impacto int4 NULL,
	prioridade_cs float8 NULL,
	gut int4 NULL,
	categoria_id int4 NULL,
	categoria varchar(50) NULL,
	id_tecnico int4 NULL,
	tecnico varchar(50) NULL,
	solicitante varchar(50) NULL,
	titulo varchar(255) NULL,
	horas_resolucao float8 NULL,
	horas_solucao float8 NULL,
	sla_esperado int4 NULL,
	sla varchar(20) NULL,
	nota_survey int4 NULL,
	comentario_survey text NULL,
	data_survey timestamp NULL,
	link_chamado varchar(255) NULL,
	tipo_chamado varchar(50) NULL,
	id_grupo_solicitante varchar(7) NULL,
	sprint int8 NULL,
	valor_orcamento numeric(15, 3) NULL,
	CONSTRAINT fglpi_chamados_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.forion_demandas (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	mes date NULL,
	squad_id int4 NULL,
	tipo varchar(20) NULL,
	chamado_id int4 NULL,
	descricao varchar(255) NULL,
	comentario varchar(255) NULL,
	is_check bool DEFAULT false NULL,
	ordem int4 DEFAULT 0 NULL,
	CONSTRAINT forion_demandas_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.forion_entrega_projetos (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	mes date NULL,
	squad_id int4 NULL,
	tipo varchar(2) NULL,
	projeto_id int4 NULL,
	prioridade int4 NULL,
	comentario varchar(255) NULL,
	texto varchar(255) NULL,
	is_check bool NULL,
	ordem int4 DEFAULT 0 NULL,
	CONSTRAINT forion_entrega_projetos_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.forion_setor_demandas (
	id serial4 NOT NULL,
	tipo varchar(50) NOT NULL,
	chamado_id int4 NULL,
	descricao text DEFAULT ''::text NOT NULL,
	comentario text DEFAULT ''::text NOT NULL,
	setor_id int4 NOT NULL,
	mes date NOT NULL,
	is_check bool DEFAULT false NOT NULL,
	ordem int4 DEFAULT 0 NOT NULL,
	CONSTRAINT forion_setor_demandas_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.forion_setor_projetos (
	id serial4 NOT NULL,
	mes date NOT NULL,
	setor_id int4 NOT NULL,
	projeto_id int4 DEFAULT 0 NOT NULL,
	prioridade int4 DEFAULT 0 NOT NULL,
	comentario text DEFAULT ''::text NOT NULL,
	texto text DEFAULT ''::text NOT NULL,
	is_check bool DEFAULT false NOT NULL,
	ordem int4 DEFAULT 0 NOT NULL,
	CONSTRAINT forion_setor_projetos_pkey PRIMARY KEY (id)
);

CREATE TABLE ti.forus_atendimento (
	sprint_id int8 NULL,
	sprint_number int4 NULL,
	status_sprint varchar(50) NULL,
	ticket_number int4 NULL,
	id int4 NULL,
	created_at timestamp NULL,
	"type" varchar(50) NULL,
	team varchar(50) NULL,
	nome_dev varchar(200) NULL,
	fase_atual varchar(100) NULL,
	planejado int4 NULL,
	total_concluidas int4 NULL,
	total_em_aberto int4 NULL,
	horas_planejadas numeric(10, 2) NULL,
	horas_apontadas numeric(10, 2) NULL
);

CREATE TABLE ti.forus_desvios_formais (
	sprint_id int4 NULL,
	sprint_number int4 NULL,
	status varchar(50) NULL,
	ticket_number int4 NULL,
	"type" varchar(50) NULL,
	team varchar(50) NULL,
	nome_dev varchar(200) NULL,
	tipo_desvio varchar(50) NULL,
	horas_apontadas numeric(10, 2) NULL
);

CREATE TABLE ti.forus_desvios_informais (
	sprint_id int4 NULL,
	sprint_number int4 NULL,
	status_sprint varchar(50) NULL,
	ticket_number int4 NULL,
	id int4 NULL,
	descricao_id varchar(100) NULL,
	created_at timestamp NULL,
	"type" varchar(50) NULL,
	team varchar(50) NULL,
	nome_dev varchar(200) NULL,
	fase_atual varchar(100) NULL,
	horas_apontadas numeric(10, 2) NULL
);

CREATE TABLE ti.forus_melhoria (
	sprint_id int4 NULL,
	sprint_number int4 NULL,
	status varchar(50) NULL,
	ticket_number int4 NULL,
	"type" varchar(50) NULL,
	team varchar(100) NULL,
	nome_dev varchar(200) NULL,
	current_phase_name varchar(100) NULL,
	planejado int4 NULL,
	total_concluidas int4 NULL,
	total_em_aberto int4 NULL,
	horas_planejadas numeric(15, 3) NULL,
	horas_apontadas numeric(15, 3) NULL
);

CREATE TABLE ti.forus_resumo_sprint (
	id numeric(10) NULL,
	sprint_number numeric(38) NULL,
	status text NULL,
	ticket_number numeric(10) NULL,
	team text NULL,
	"nome dev" text NULL,
	current_phase_name text NULL,
	planejado numeric(38, 10) NULL,
	total_concluidas numeric(38, 10) NULL,
	total_em_aberto numeric(38, 10) NULL,
	"horas planejadas" numeric(38, 10) NULL,
	"horas apontadas" numeric(38, 10) NULL
);

CREATE TABLE ti.forus_sprint (
	id int4 NULL,
	sprint_number int4 NULL,
	active int4 NULL,
	"name" varchar(150) NULL,
	description text NULL,
	start_date date NULL,
	end_date date NULL,
	status varchar(50) NULL,
	team varchar(50) NULL,
	available_hours numeric(10, 2) NULL,
	total_hours numeric(10, 2) NULL,
	worked_hours numeric(10, 2) NULL
);